let elX={src:'up',type:'tent',loc:'n',prov:'all'};
const cmpC=(a,b)=>String(a.last||lf(a.name).split(',')[0]).toLowerCase().localeCompare(String(b.last||lf(b.name).split(',')[0]).toLowerCase());
const ACR=(P,p)=>p<0||!P[p]?'IND':acr(P[p]);
const cnm=(c,P)=>`${c.first&&c.last?esc(c.last)+', '+esc(c.first):esc(lf(c.name))} (${ACR(P,c.party)})`;
const srcOpts=()=>{const o=[];if(S.cands&&S.cands.pub)o.push(['up','Upcoming election, '+fday(S.next)+' (candidate lists)']);S.elections.filter(r=>r.F&&r.F.done).forEach(r=>o.push([String(r.id),r.label+' ('+r.d+')']));return o};
function curSrc(){const o=srcOpts();if(!o.length)return null;if(!o.some(x=>x[0]==elX.src))elX.src=o[0][0];if(elX.src=='up')return{F:S.cands,R:null,done:false};const R=S.elections.find(r=>String(r.id)==elX.src);return{F:R.F,R,done:true}}
const FILES=[['tent','Tentative List of Candidates'],['bal','Ballot Face Template'],['coc','Certificate of Canvass'],['elected','List of Elected Local Candidates'],['turn','Voter Turnout']];
const dhead=(t,sub)=>`<div style="display:flex;gap:12px;align-items:center;margin-bottom:6px">${flag(S.flagSd,84)}<div><div class="mut">Commission on Elections, ${esc(S.nation.name)}</div><h2 style="margin:0">${esc(t)}</h2><div class="mut">${sub}</div></div></div>`;
const sortC=L=>(L||[]).slice().sort(cmpC);
const nlist=(t,L,P,seats)=>`<h3>${t}${seats>1?` (vote for not more than ${seats})`:''}</h3><table class="tbl">${sortC(L).map((c,i)=>`<tr><td style="width:2.5em">${i+1}</td><td>${cnm(c,P)}</td></tr>`).join('')}</table>`;
const prow=(t,L,P,seats,valid)=>`<h3>${t}${seats>1?` (${seats} seats)`:''}</h3><table class="tbl"><tr><th>Candidate (party)</th><th>Votes</th><th>Share</th><th></th></tr>${(L||[]).slice().sort((a,b)=>b.votes-a.votes).map(c=>`<tr><td>${cnm(c,P)}</td><td>${fmt(c.votes||0)}</td><td>${valid?((c.votes||0)/(valid*(seats>1?seats*.85:1))*100).toFixed(1)+'%':''}</td><td>${c.won?'<b>Proclaimed</b>':''}</td></tr>`).join('')}</table>`;
const sig=t=>`<table class="tbl" style="margin-top:14px"><tr><td>Chairperson: ____________________</td><td>Member: ____________________</td></tr><tr><td>Member: ____________________</td><td>Secretary: ____________________</td></tr></table><p class="mut">${t}</p>`;
const turnTbl=(reg,bal,val)=>`<table class="tbl"><tr><td>Registered voters</td><td>${fmt(reg)}</td></tr><tr><td>Votes cast (ballots)</td><td>${fmt(bal)}</td></tr><tr><td>Valid votes</td><td>${fmt(val)}</td></tr><tr><td><b>Voter turnout</b></td><td><b>${reg?(bal/reg*100).toFixed(2):0}%</b></td></tr></table>`;
function docTent(c,loc){const F=c.F,P=F.P;let h=dhead('Tentative List of Candidates',loc=='n'?'National positions':loc[0]=='p'?esc((F.prov[loc.slice(2)]||{}).name||'')+' Province':esc((F.mun[loc.slice(2)]||{}).name||''));
 if(loc=='n'){if(F.nat.pres)h+=nlist('President',F.nat.pres,P)+nlist('Vice President',F.nat.vp,P);h+=nlist('Senators',F.nat.sen.c,P,F.nat.sen.seats)+`<h3>Party-list groups and nominees</h3><table class="tbl"><tr><th>Group</th><th>Kind</th><th>Affiliation</th><th>Nominees (in ranking order)</th></tr>${F.nat.pl.map(g=>`<tr><td>${esc(g.name)}</td><td>${esc(g.kind||'')}</td><td>${ACR(P,g.party)}</td><td>${g.nominees.slice(0,8).map(n=>esc(lf(n))).join('; ')}</td></tr>`).join('')}</table>`}
 else if(loc[0]=='p'){const e=F.prov[loc.slice(2)];if(!e)return h+'<p>No data.</p>';h+=nlist('Governor',e.gov,P)+nlist('Vice Governor',e.vg,P)+e.hr.map(r=>nlist(`Member, House of Representatives, District ${r.d}`,r.c,P)).join('')+e.sp.map(r=>nlist(`Sangguniang Panlalawigan Member, Provincial District ${r.pd}`,r.c,P,r.seats)).join('')}
 else{const e=F.mun[loc.slice(2)];if(!e)return h+'<p>No data.</p>';h+=nlist('Mayor',e.my,P)+nlist('Vice Mayor',e.vm,P)+nlist(e.city?'Sangguniang Panlungsod Member':'Sangguniang Bayan Member',e.sb.c,P,e.sb.seats)}
 return h+'<p class="mut">Candidates are listed alphabetically by last name. This is a tentative list; the certified list follows after petitions are resolved (Omnibus Election Code Secs. 7 and 78).</p>'}
function docBallot(c,loc){const F=c.F,P=F.P;let mid=loc[0]=='m'?+loc.slice(2):null;if(mid==null){const p=loc[0]=='p'?S.provs[+loc.slice(2)]:null;mid=p&&p.mun.length?p.mun[0]:(S.munis[0]||{}).id}const m=F.mun[mid];if(!m)return dhead('Ballot Face Template','')+'<p>Choose a city or municipality.</p>';
 const prov=F.prov[m.prov]||{},p=S.provs[m.prov],sec=(t,note,L,pp)=>`<div class="bsec"><div class="bh"><b>${t}</b><span>${note}</span></div><div class="bl">${sortC(L).map((x,i)=>`<div class="bc"><span class="bn">${i+1}</span><span class="oval"></span>${cnm(x,pp||P)}</div>`).join('')}</div></div>`;
 let h=dhead('Official Ballot Face Template',`${esc(m.name)}, ${esc(prov.name||'')}. Fill the oval beside each chosen candidate.`)+'<div class="ballot">';
 if(F.nat.pres)h+=sec('President','Vote for 1',F.nat.pres)+sec('Vice President','Vote for 1',F.nat.vp);h+=sec('Senators',`Vote for not more than ${F.nat.sen.seats}`,F.nat.sen.c);
 h+=`<div class="bsec"><div class="bh"><b>Party-list</b><span>Vote for 1</span></div><div class="bl">${F.nat.pl.slice().sort((a,b)=>a.name.localeCompare(b.name)).map((g,i)=>`<div class="bc"><span class="bn">${i+1}</span><span class="oval"></span>${esc(g.name)} <span class="mut">${esc(g.kind||'')}</span></div>`).join('')}</div></div>`;
 const hr=(prov.hr||[]).find(r=>(r.munis||[]).includes(m.name));if(hr)h+=sec(`Member, House of Representatives, District ${hr.d}`,'Vote for 1',hr.c);
 if(m.huc||m.icc)h+=`<p class="mut">${m.huc?'Highly urbanized city':'Independent component city'} voters do not vote for provincial officials (Omnibus Election Code Sec. 30).</p>`;
 else{h+=sec('Governor','Vote for 1',prov.gov||[])+sec('Vice Governor','Vote for 1',prov.vg||[]);const pd=((p&&p.pds)||[]).find(d=>d.munis.includes(+mid)),r=pd&&(prov.sp||[]).find(x=>x.pd==pd.n);if(r)h+=sec(`Sangguniang Panlalawigan Member, Provincial District ${r.pd}`,`Vote for not more than ${r.seats}`,r.c)}
 h+=sec('Mayor','Vote for 1',m.my)+sec('Vice Mayor','Vote for 1',m.vm)+sec(m.city?'Sangguniang Panlungsod Member':'Sangguniang Bayan Member',`Vote for not more than ${m.sb.seats}`,m.sb.c);
 return h+'</div><p class="mut">Candidates appear alphabetically by last name, regardless of party. Marking more than the allowed number of ovals spoils that position.</p>'}
function docCoc(c,loc){if(!c.done)return dhead('Certificate of Canvass','')+'<p>Certificates of canvass exist after election day.</p>';const F=c.F,P=F.P,N=F.nat;let h=dhead('Certificate of Canvass of Votes and Proclamation of Winning Candidates',c.R.d);
 if(loc=='n'){h+=turnTbl(N.reg,N.bal,N.val);if(N.pres)h+=prow('President',N.pres,P,1,N.val)+prow('Vice President',N.vp,P,1,N.val);h+=prow('Senators',N.sen.c.slice(0,N.sen.seats+6),P,N.sen.seats,N.val)+`<h3>Party-list</h3><table class="tbl"><tr><th>Group</th><th>Votes</th><th>Seats</th></tr>${N.pl.map(g=>`<tr><td>${esc(g.name)}</td><td>${fmt(g.votes||0)}</td><td>${g.seats||0}</td></tr>`).join('')}</table>`;return h+sig('National Board of Canvassers (Congress for President and Vice President, Art. VII Sec. 4).')}
 if(loc[0]=='p'){const id=+loc.slice(2),e=F.prov[id];if(!e)return h+'<p>No data.</p>';h+=`<h3>${esc(e.name)} Province: Provincial Board of Canvassers</h3>`+turnTbl(e.reg,e.bal,e.val);
  const pv=(L,pvm)=>L.map(x=>({...x,votes:pvm&&pvm[id]?pvm[id][x.ix]:0}));if(N.presPv)h+=prow('President (this province)',pv(N.pres,N.presPv),P,1,e.val)+prow('Vice President (this province)',pv(N.vp,N.vpPv),P,1,e.val);
  if(N.sen.pv)h+=prow('Senators (this province, top 12)',pv(N.sen.c,N.sen.pv).sort((a,b)=>b.votes-a.votes).slice(0,12).map(x=>({...x,won:0})),P,N.sen.seats,e.val);
  h+=prow('Governor',e.gov,P,1,e.elect)+prow('Vice Governor',e.vg,P,1,e.elect)+e.hr.map(r=>`<p class="mut">District ${r.d}: ${esc((r.munis||[]).join(', '))}. Registered voters ${fmt(r.reg||0)}; valid votes ${fmt(r.val||0)}; turnout of valid votes to registered ${r.reg?((r.val/r.reg)*100).toFixed(1):0}%.</p>`+prow(`Member, House of Representatives, District ${r.d}`,r.c,P,1,r.val)).join('')+e.sp.map(r=>prow(`Sangguniang Panlalawigan, Provincial District ${r.pd}`,r.c,P,r.seats,r.valid)).join('');return h+sig('Provincial Board of Canvassers.')}
 const e=F.mun[+loc.slice(2)];if(!e)return h+'<p>No data.</p>';h+=`<h3>${esc(e.name)}: ${e.huc?'City':e.city?'City':'Municipal'} Board of Canvassers</h3>`+turnTbl(e.reg,e.bal,e.val)+prow('Mayor',e.my,P,1,e.val)+prow('Vice Mayor',e.vm,P,1,e.val)+prow(e.city?'Sangguniang Panlungsod':'Sangguniang Bayan',e.sb.c,P,e.sb.seats,e.val);return h+sig('City or Municipal Board of Canvassers.')}
function docElected(c){if(!c.done)return dhead('List of Elected Local Candidates','')+'<p>Winners are known after election day.</p>';const F=c.F,P=F.P,pf=elX.prov=='all'?null:+elX.prov;let h=dhead('List of Elected Local Candidates',c.R.d+(pf==null?'. All provinces.':'. '+esc((F.prov[pf]||{}).name||'')));
 const won=L=>(L||[]).filter(x=>x.won),row=(pos,loc,x)=>`<tr><td>${pos}</td><td>${esc(loc)}</td><td>${cnm(x,P)}</td><td>${fmt(x.votes||0)}</td></tr>`;let rows='';
 Object.keys(F.prov).forEach(id=>{if(pf!=null&&+id!=pf)return;const e=F.prov[id];won(e.gov).forEach(x=>rows+=row('Governor',e.name,x));won(e.vg).forEach(x=>rows+=row('Vice Governor',e.name,x));e.hr.forEach(r=>won(r.c).forEach(x=>rows+=row('Representative',`${e.name}, District ${r.d}`,x)));e.sp.forEach(r=>won(r.c).forEach(x=>rows+=row('Provincial Board Member',`${e.name}, District ${r.pd}`,x)))});
 Object.keys(F.mun).forEach(id=>{const e=F.mun[id];if(pf!=null&&e.prov!=pf)return;won(e.my).forEach(x=>rows+=row('Mayor',e.name,x));won(e.vm).forEach(x=>rows+=row('Vice Mayor',e.name,x));won(e.sb.c).forEach(x=>rows+=row('Councilor',e.name,x))});
 return h+`<table class="tbl"><tr><th>Position</th><th>Locality</th><th>Elected (party)</th><th>Votes</th></tr>${rows}</table>`}
function docTurn(c,loc){if(!c.done)return dhead('Voter Turnout','')+'<p>Turnout is recorded after election day.</p>';const F=c.F,N=F.nat,bar=t=>`<div class="meter"><div style="width:${Math.min(100,t)}%"></div></div>`;let h=dhead('Registered Voters and Votes Cast (Voter Turnout)',c.R.d)+turnTbl(N.reg,N.bal,N.val);
 const rowT=(n,r,b,v)=>`<tr><td>${esc(n)}</td><td>${fmt(r)}</td><td>${fmt(b)}</td><td>${fmt(v)}</td><td style="min-width:90px">${r?(b/r*100).toFixed(1):0}%${bar(r?b/r*100:0)}</td></tr>`,hd='<tr><th>Area</th><th>Registered</th><th>Ballots cast</th><th>Valid votes</th><th>Turnout</th></tr>';
 if(loc[0]=='p'){const id=+loc.slice(2);h+=`<h3>${esc((F.prov[id]||{}).name||'')}: cities and municipalities</h3><table class="tbl">${hd}${Object.keys(F.mun).filter(k=>F.mun[k].prov==id).map(k=>rowT(F.mun[k].name,F.mun[k].reg,F.mun[k].bal,F.mun[k].val)).join('')}</table>`}
 else if(loc[0]=='m'){const e=F.mun[+loc.slice(2)];if(e)h+=turnTbl(e.reg,e.bal,e.val)}
 else h+=`<h3>By province</h3><table class="tbl">${hd}${Object.keys(F.prov).map(k=>rowT(F.prov[k].name,F.prov[k].reg,F.prov[k].bal,F.prov[k].val)).join('')}</table>`;
 const tr=S.elections.filter(r=>r.F&&r.F.done).slice().reverse();return h+`<h3>Turnout over time</h3><table class="tbl"><tr><th>Election</th><th>Registered</th><th>Ballots cast</th><th>Turnout</th></tr>${tr.map(r=>`<tr><td>${esc(r.label)}</td><td>${fmt(r.F.nat.reg)}</td><td>${fmt(r.F.nat.bal)}</td><td>${(r.F.nat.bal/r.F.nat.reg*100).toFixed(1)}%</td></tr>`).join('')}</table>`}
function elDoc(){const c=curSrc();if(!c)return '<p class="mut">No candidate lists yet. Lists are prepared when the filing of certificates of candidacy closes (see the calendar).</p>';
 const t=elX.type;if(t=='tent'&&c.F.pub===false)return '<p class="mut">The tentative list has not been published yet.</p>';if(t=='bal'&&c.R==null&&!c.F.bft&&!c.F.pub)return '<p class="mut">The ballot face template is not approved yet.</p>';
 let h=t=='tent'?docTent(c,elX.loc):t=='bal'?docBallot(c,elX.loc):t=='coc'?docCoc(c,elX.loc):t=='elected'?docElected(c):docTurn(c,elX.loc);return `<div class="report">${h}</div>`}
function locSel(types){const o=[];if(types.includes('n'))o.push(['n','Nation']);if(types.includes('p')||types.includes('m'))S.provs.forEach(p=>{const g=[];if(types.includes('p'))g.push(['p:'+p.id,p.name+' Province']);if(types.includes('m'))p.mun.forEach(id=>g.push(['m:'+id,S.munis[id].name]));o.push(g)});
 if(!o.flat?.(2)||true){}const ok=x=>Array.isArray(x[0]);const valid=[];o.forEach(x=>{if(ok(x))x.forEach(y=>valid.push(y[0]));else valid.push(x[0])});if(!valid.includes(elX.loc))elX.loc=valid[0]||'n';
 return `<select id="elloc">${o.map(x=>ok(x)?`<optgroup label="${esc(S.provs[+x[0][0].split(':')[1]]?(x[0][0][0]=='p'?S.provs[+x[0][0].slice(2)].name:S.provs[S.munis[+x[0][0].slice(2)].prov].name):'')}">${x.map(y=>`<option value="${y[0]}" ${y[0]==elX.loc?'selected':''}>${esc(y[1])}</option>`).join('')}</optgroup>`:`<option value="${x[0]}" ${x[0]==elX.loc?'selected':''}>${esc(x[1])}</option>`).join('')}</select>`}
function calHTML(){if(!S.cal)buildCal();const up=S.cal.ev.filter(e=>e.d>=S.dt-45&&e.d<=S.dt+400);return `<table class="tbl"><tr><th>Date</th><th>Activity</th><th>Basis</th><th></th></tr>${up.map(e=>`<tr><td>${fday(e.d)}</td><td>${esc(e.label)}</td><td>${esc(e.basis)}</td><td>${e.d<S.dt?'Done':e.d==S.dt?'Today':'in '+(e.d-S.dt)+' days'}</td></tr>`).join('')}</table><p class="mut">Dates follow the Omnibus Election Code (BP 881) and RA 7166. Where the Code leaves the date to COMELEC's calendar (Sec. 7), the simulation sets a typical date. Election day is the second Monday of May (RA 7166 Sec. 3).</p>`}
function electionsView(){const c=curSrc(),o=srcOpts(),t=elX.type,locTypes=t=='bal'?['m']:t=='tent'||t=='coc'||t=='turn'?['n','p','m']:[];
 return `<h2>Elections</h2><p class="mut">Candidate lists, ballots, canvass, and results follow the election calendar. Use Export PDF, then choose Save as PDF in the print dialog.</p>
 <h3>Election calendar</h3>${calHTML()}
 <h3>Election files</h3><div class="sub">${FILES.map(([k,n])=>`<button data-eft="${k}" aria-pressed="${t==k}">${n}</button>`).join('')}</div>
 <div class="sub"><select id="elsrc">${o.map(x=>`<option value="${x[0]}" ${x[0]==elX.src?'selected':''}>${esc(x[1])}</option>`).join('')||'<option>No election data yet</option>'}</select>${locTypes.length?locSel(locTypes):''}${t=='elected'?`<select id="elprov"><option value="all">All provinces</option>${S.provs.map(p=>`<option value="${p.id}" ${elX.prov==p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select>`:''}<button data-act="elpdf">Export PDF</button></div>
 <div id="eldoc">${elDoc()}</div>
 <h3>Results</h3><ul>${S.elections.map(r=>`<li class="ed" style="cursor:default"><b>${esc(r.label)}</b><span><button data-view="${r.id}">View</button> <button data-pdf="${r.id}">Export PDF</button></span></li>`).join('')||'<li class="ed" style="cursor:default">No elections yet.</li>'}</ul>${rep?reportHTML(rep):''}`}
function elAfter(){const a=$('#elsrc'),l=$('#elloc'),p=$('#elprov'),d=()=>{$('#eldoc').innerHTML=elDoc()};if(a)a.onchange=()=>{elX.src=a.value;render()};if(l)l.onchange=()=>{elX.loc=l.value;d()};if(p)p.onchange=()=>{elX.prov=p.value;d()}}
