const D=()=>new Date(Date.UTC(S.y0,0,1+S.dt));
const fday=n=>new Date(Date.UTC(S.y0,0,1+n)).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'});
const dstr=()=>fday(S.dt),yr=()=>D().getUTCFullYear();
const dn=(y,m,d,y0)=>Math.round((Date.UTC(y,m,d)-Date.UTC(y0,0,1))/864e5);
const elecDay=(y,y0)=>{const w=new Date(Date.UTC(y,4,1)).getUTCDay();return dn(y,4,1+(1-w+7)%7+7,y0)};
const bskeDay=(y,y0)=>{const w=new Date(Date.UTC(y,10,1)).getUTCDay();return dn(y,10,1+(1-w+7)%7+7,y0)};
const openDay=(y,y0)=>{const w=new Date(Date.UTC(y,6,1)).getUTCDay();return dn(y,6,1+(1-w+7)%7+21,y0)};
const inSession=()=>{const y=yr(),op=openDay(y,S.y0);return S.dt>=op||S.dt<op-30};
const log=t=>{S.news.unshift(`${dstr()}: ${t}`);S.news.length=Math.min(S.news.length,80)};
const z=()=>S.parties.map(()=>0);
function wt(e,inc){const mood=(S.stats.approval-50)/100;return e.lean.map((x,i)=>Math.pow(x*(1+(i==S.pres.party?mood:-mood/4))*(i==inc?1.3:1),1.5))}
function re(o,w,lim,mk,lo){const p=sample(w);if(p==o.party&&rnd()<.6&&(o.terms||1)<lim&&(!lo||o.by==null||curY()-o.by>=lo)){o.terms=(o.terms||1)+1;return o}return mk?mk(p):{name:nm(),party:p,terms:1}}
const houseCounts=()=>{const c=z();S.house.forEach(r=>c[r.party]++);return c};
const senCounts=()=>tally(S.senate).slice(0,S.parties.length);
function natW(){const t=z();S.provs.forEach(p=>wt(p,-1).forEach((x,i)=>t[i]+=x*p.pop));return norm(t)}
const addLog=(b,t)=>{b.log.unshift(`${dstr()}: ${t}`);b.log.length=Math.min(b.log.length,12)};
function score(m,b,art,sec){const t=art||b,tg=t.tags||[];let s=.8-Math.abs(m.ideo-t.i)*1.1+(tg.some(x=>m.int.includes(x))?.3:0)+(rnd()-.5)*.4;
 if((t.e||{}).corruption>0)s-=m.integ*.5;
 if(!sec)s+=m.loyal*((m.party==b.spp?.25:0)+(m.party==S.pres.party?.1:-.05));
 if(b.mine)s+=(m.trust-50)/100*(S.crisis>0?1:.6);return s}
function ballot(list,b,art,sec,need){let y=0,n=0,a=0;const v=list.map(m=>{const s=score(m,b,art,sec);if(Math.abs(s)<.07){a++;return 0}if(s>0){y++;return 1}n++;return -1}),maj={};
 list.forEach((m,i)=>{if(v[i]){const q=maj[m.party]=maj[m.party]||[0,0];q[v[i]>0?0:1]++}});
 const reb=list.filter((m,i)=>v[i]&&((v[i]>0)!=(maj[m.party][0]>=maj[m.party][1]))).slice(0,4);
 if(b.mine)list.forEach((m,i)=>{if(v[i])m.trust=cl(m.trust+(v[i]>0?1.5:-1),0,100)});
 return{y,n,a,tot:list.length,pass:need?y>=need*list.length:y>n,reb}}
const vtxt=(l,r,sec)=>`${l}${sec?' (secret ballot)':''}: ${r.y} yes, ${r.n} no, ${r.a} abstain of ${r.tot}. ${r.pass?'Passed':'Failed'}.${r.reb.length?' Defied their party: '+r.reb.map(m=>m.name).join(', ')+'.':''}`;
const ORD=o=>o=='H'?['H-Com','H-2nd','H-3rd','S-Com','S-3rd']:['S-Com','S-3rd','H-Com','H-2nd','H-3rd'];
const nextSt=b=>{if(b.st=='Bicam')return'Pres';const o=ORD(b.orig),i=o.indexOf(b.st);return i<o.length-1?o[i+1]:(b.kind=='amend'?'Plebiscite':'Bicam')};
const cmtOf=b=>S.committees.find(c=>c.tag==b.tags[0])||S.committees[0];
function calc(b){b.i=b.arts.reduce((s,a)=>s+a.i,0)/b.arts.length;b.tags=[...new Set(b.arts.flatMap(a=>a.tags))];b.e={};b.arts.forEach(a=>{for(const k in a.e)b.e[k]=(b.e[k]||0)+a.e[k]});b.kind=b.entr||b.arts.some(a=>a.c)?'amend':'law'}
function makeBill(o){const arts=o.arts||o.ids.map(id=>({...ART_LIB.find(a=>a.id==id)}));arts.forEach(a=>{a.ok=null;a.tags=a.tags||[];a.e=a.e||{}});
 const sp=o.sp||{ch:'H',i:Math.floor(rnd()*S.house.length)},m=(sp.ch=='H'?S.house:S.senate)[sp.i],b={id:S.nbid++,t:o.title,arts,sp,spn:m.name,spp:m.party,mine:!!o.mine,urgent:!o.mine&&rnd()<.05,dm:S.dt,entr:!!o.entr,repeals:o.repeals||0,log:[]};
 calc(b);b.orig=b.tags.some(t=>t=='budget'||t=='revenue')?'H':(o.orig||pick(['H','S']));b.st=ORD(b.orig)[0];S.bills.unshift(b);addLog(b,`Filed by ${m.name} in the ${b.orig=='H'?'House':'Senate'}.`);return b}
function draft(t0){const [t,ids]=t0||(rnd()<.06?pick(BT.slice(11)):pick(BT.slice(0,11)));if(S.bills.some(b=>b.t==t&&STN[b.st]))return;const b=makeBill({title:t,ids});log(`${b.spn} files "${t}".`)}
function artVote(b,k,sec,force){const a=b.arts[k];if(force==null){const r=ballot(S.house,b,a,sec);a.ok=r.pass;addLog(b,vtxt('Article '+(k+1),r,sec))}else{a.ok=!!force;addLog(b,`Article ${k+1} ${force?'approved':'struck'} by the floor leader.`)}}
function closeSecond(b){b.arts.forEach((a,k)=>{if(a.ok==null)artVote(b,k,false)});const keep=b.arts.filter(a=>a.ok);if(!keep.length){b.st='Failed';addLog(b,'All articles were struck. The bill dies.');return}b.arts=keep;calc(b);b.st=nextSt(b);addLog(b,`Second reading closed with ${keep.length} article(s).`)}
function applyArts(b,k){b.arts.forEach(a=>{for(const x in a.e)S.stats[x]=+cl((S.stats[x]||0)+a.e[x]*(k||1),x=='treasury'||x=='growth'?-20:0,x=='treasury'?999:x=='growth'?20:100).toFixed(2);if(a.c&&k!=-1)applyCon(a.c);localFx(a,k)})}
function enact(b,t){b.st='Law';addLog(b,t);if(b.repeals){const o=S.bills.find(x=>x.id==b.repeals);if(o){o.st='Repealed';addLog(o,'Repealed by "'+b.t+'".')}}log(`"${b.t}" becomes law.`);applyArts(b);registerLaw(b);
 if(b.kind=='law'&&rnd()<.25){const n=S.justices.filter(j=>Math.abs(j.lean-b.i)>.8).length;if(n>S.justices.length/2){b.st='Struck down';applyArts(b,-1);addLog(b,`The Supreme Court strikes the law down (${n} to ${S.justices.length-n}).`);log(`The Supreme Court strikes down "${b.t}".`)}else addLog(b,`The Supreme Court upholds the law (${S.justices.length-n} to ${n}).`)}}
function fail(b,ai){if(ai&&rnd()<.4&&!/^General Appropriations/.test(b.t)){b.st='Failed';addLog(b,'The bill dies.')}}
function act(b,sec,ai){const s0=b.st;act0(b,sec,ai);if(b.st!=s0)b.dm=S.dt}
const attend=L=>{const p=L.filter(()=>rnd()<S.rules.attend);return p.length>L.length*S.rules.quorum/100?p:null};
function act0(b,sec,ai){if(!['Pres','Plebiscite'].includes(b.st)&&!inSession()){if(!ai)addLog(b,'Congress is in recess; the vote is postponed (Art. VI Sec. 15).');return}
 const st=b.st,ch=st[0],need=b.kind=='amend'&&st.endsWith('3rd')?S.con.amendVote/100:0;let r;
 if(st=='H-Com'||st=='S-Com'){const c=cmtOf(b),list=ch=='H'?c.mem.map(i=>S.house[i]).filter(Boolean):S.senate.filter((_,i)=>i%3==b.id%3),sp=S.house[S.speaker];
  if(ch=='H'&&!b.mine&&sp&&sp.party!=b.spp&&rnd()<.25){addLog(b,'The Speaker keeps the bill pending in committee.');return}
  r=ballot(list,b,null,sec);addLog(b,vtxt(ch=='H'?c.name+' committee':'Senate committee',r,sec));if(r.pass)b.st=nextSt(b);else fail(b,ai)}
 else if(st=='H-2nd')closeSecond(b);
 else if(st.endsWith('3rd')){if(S.rules.sepDays&&!b.urgent&&b.dm!=null&&S.dt-b.dm<S.rules.printDays){addLog(b,`Third reading must wait ${S.rules.printDays} days after the final bill is distributed, unless the President certifies urgency (Art. VI Sec. 26).`);return}
  const L=ch=='H'?S.house:S.senate,pr=attend(L);if(!pr){addLog(b,'No quorum: a majority of members is not present (Art. VI Sec. 16). The vote is deferred.');return}
  r=ballot(pr,b,null,sec,need?need*L.length/pr.length:0);addLog(b,vtxt((ch=='H'?'House':'Senate')+' third reading',r,sec));if(r.pass)b.st=nextSt(b);else fail(b,ai)}
 else if(st=='Bicam'){const c=cmtOf(b),l=c.mem.slice(0,3).map(i=>S.house[i]).filter(Boolean).concat(S.senate.slice(b.id%20,b.id%20+3));r=ballot(l,b,null,sec);addLog(b,vtxt('Bicameral conference committee',r,sec));if(r.pass)b.st='Pres';else fail(b,ai)}
 else if(st=='Pres'){if(1-Math.abs(S.pres.ideo-b.i)*.9+(rnd()-.4)>.35)enact(b,'The President signs the bill.');else if(b.tags.includes('budget')&&b.arts.length>1){const a=b.arts.splice(Math.floor(rnd()*b.arts.length),1)[0];calc(b);addLog(b,`Line-item veto of "${a.t}" (Art. VI Sec. 27).`);enact(b,'The President signs the rest of the appropriation.')}else{b.st='Vetoed';addLog(b,'The President vetoes the bill.')}}
 else if(st=='Plebiscite'){const y=50+(S.stats.approval-50)*.4+(rnd()-.5)*24;addLog(b,`Plebiscite: ${y.toFixed(1)}% yes (${S.con.plebiscite}% needed).`);if(y>S.con.plebiscite){b.st='Ratified';applyArts(b);log(`Voters ratify "${b.t}".`)}else{b.st='Failed';log(`Voters reject "${b.t}".`)}}
 else if(st=='Vetoed'&&!b.ov){b.ov=1;const o=S.con.vetoOverride/100,h=ballot(S.house,b,null,sec,o),s=ballot(S.senate,b,null,sec,o);addLog(b,vtxt('Override, House',h,sec)+' '+vtxt('Override, Senate',s,sec));if(h.pass&&s.pass)enact(b,'Congress overrides the veto.')}}
function applyCon(c){const sp=S.house[S.speaker];Object.assign(S.con,c);log('The Constitution is amended: '+Object.keys(c).map(k=>`${CONL[k][0]} is now ${c[k]}`).join('; ')+'.');
 while(S.senate.length<S.con.senSize)S.senate.push({...mem(sample(natW()),S.parties),cls:S.senate.length%2});S.senate.length=Math.min(S.senate.length,S.con.senSize);
 while(S.justices.length<S.con.scSize)S.justices.push({name:nm(),role:'Associate Justice',lean:+(rnd()*2-1).toFixed(1)});S.justices.length=Math.min(S.justices.length,S.con.scSize);
 rebuildPL();rebuildCmt();S.speaker=Math.max(0,S.house.indexOf(sp))}
function electSpeaker(forced){const H=S.house,cands=S.parties.map((p,i)=>{let b=-1,bt=-1;H.forEach((m,j)=>{if(m.party==i&&m.terms*10+m.integ>bt){bt=m.terms*10+m.integ;b=j}});return b}).filter(j=>j>=0);
 if(forced!=null&&!cands.includes(forced))cands.push(forced);
 const vote=cs=>{const t=cs.map(()=>0);H.forEach(m=>{let bs=-9,bi=0;cs.forEach((j,k)=>{const c=H[j],s=(m.party==c.party?.9*m.loyal+.3:0)-Math.abs(m.ideo-c.ideo)*.8+(c.party==S.player.party?(m.trust-50)/150:0)+(rnd()-.5)*.3;if(s>bs){bs=s;bi=k}});t[bi]++});return t};
 let t=vote(cands),w=cands[t.indexOf(Math.max(...t))],txt=`${t.join(', ')} votes`;
 if(Math.max(...t)<=H.length/2){const top=cands.map((j,k)=>[t[k],j]).sort((a,b)=>b[0]-a[0]).slice(0,2).map(x=>x[1]);t=vote(top);w=top[t.indexOf(Math.max(...t))];txt+=`; runoff ${t.join(' to ')}`}
 S.speaker=w;log(`${H[w].name} is elected Speaker of the House (${txt}).`);leaders()}
function repealBill(b){if(!Object.keys(b.e).length)return null;return makeBill({title:'Repeal of '+b.t,arts:b.arts.map(a=>({...a,t:'Repeal: '+a.t,i:-a.i,c:undefined,ok:null,e:Object.fromEntries(Object.entries(a.e).map(([k,v])=>[k,-v]))})),orig:'H',sp:{ch:'H',i:Math.max(0,S.house.findIndex(m=>m.party==S.player.party))},mine:true,entr:b.entr,repeals:b.id})}
function impeach(sec){if(!inSession()){log('Congress is in recess; no impeachment vote can be held (Art. VI Sec. 15).');return}
 if(S.imp&&S.imp.d>S.dt-365){log('Only one impeachment proceeding may be initiated against the same official within a year (Art. XI Sec. 3).');return}
 const sc=(m,th)=>(m.party!=S.pres.party?.3:-.5)*(sec?.5:1)+(S.stats.corruption-40)/90-(S.stats.approval-50)/110+(m.integ-.5)*.3+(rnd()-.5)*.3>th;
 const y=S.house.filter(m=>sc(m,.15)).length,need=Math.ceil(S.con.impHouse/100*S.house.length);S.imp={d:S.dt};
 log(`Impeachment of ${S.pres.name}: ${y} of ${S.house.length} House members vote to impeach${sec?' (secret ballot)':''}; ${need} needed.`);
 if(y<need){log('The complaint fails in the House.');return}
 const c=S.senate.filter(m=>sc(m,.3)).length,n2=Math.ceil(S.con.impSenate/100*S.senate.length);log(`Senate trial: ${c} of ${S.senate.length} senators vote to convict; ${n2} needed.`);
 if(c>=n2){log(`${S.pres.name} is removed from office. ${S.vp.name} becomes President.`);S.pres=S.vp;S.vp=nominateVP();S.stats.approval=50}else{log(`${S.pres.name} is acquitted.`);S.stats.approval=cl(S.stats.approval-2,0,100)}}
function rally(){S.house.concat(S.senate).forEach(m=>{if(m.party==S.player.party)m.trust=cl(m.trust+8,0,100)});S.crisis=Math.max(0,S.crisis-15);log('You rally your lawmakers behind the government.')}
function fixBg(){const M=S.map;if(!M.bg)initBrgyMap(S);const bad={};for(let i=0;i<W*H;i++){const m=M.mun[i];if(m>=0&&M.land[i]){const mm=S.munis[m];if(mm&&(M.bg[i]<0||M.bg[i]>=mm.brgy.length))(bad[m]=bad[m]||[]).push(i)}}
 for(const mi in bad){const m=S.munis[mi],cb=bgCells(m),cen=cb.map(c=>c.length?[c.reduce((a,i)=>a+i%W,0)/c.length,c.reduce((a,i)=>a+(i/W|0),0)/c.length]:null);if(!cen.some(Boolean)){layoutBrgys(S,m);continue}bad[mi].forEach(i=>{const x=i%W,y=i/W|0;let b=0,bd=1e9;cen.forEach((q,j)=>{if(q){const d=(q[0]-x)**2+(q[1]-y)**2;if(d<bd){bd=d;b=j}}});M.bg[i]=b})}}
function syncGeo(){fixBg();const M=S.map,n0=S.house.filter(r=>r.prov>=0).length;for(let i=0;i<W*H;i++)if(M.land[i]&&M.mun[i]>=0)M.prov[i]=S.munis[M.mun[i]].prov;
 S.provs.forEach(p=>p.mun=[]);S.munis.forEach(m=>{S.provs[m.prov].mun.push(m.id);const t=m.huc?12:m.city?10:8;while(m.sb.length<t)m.sb.push(person(m.lean));m.sb.length=t});
 S.provs.forEach(fixDistricts);S.munis.forEach(m=>{if(m.huc)m.city=true;const t=lguType(m);if(!m.ic||!m.ic.incomeClass.endsWith(t))reclassOne(m,t)});S.provs.forEach(fixProvDistricts);fixCaps();S.provs.forEach(p=>{const have=S.house.filter(r=>r.prov==p.id).length;for(let k=have;k<p.dist;k++)S.house.push({prov:p.id,d:k+1,...mem(sample(p.lean),S.parties)});let rm=have-p.dist;for(let i=S.house.length-1;i>=0&&rm>0;i--)if(S.house[i].prov==p.id){S.house.splice(i,1);rm--}});
 if(S.house.filter(r=>r.prov>=0).length!=n0){rebuildPL();rebuildCmt();S.speaker=Math.min(S.speaker,S.house.length-1)}}
const hist=(e,o)=>{e.hist=e.hist||[];e.hist.unshift(`${yr()}: ${o.name} (${S.parties[o.party].name})`);e.hist.length=Math.min(e.hist.length,4)};
const regV=pop=>Math.round(pop*Math.max(.4,.62-(((S.rules||{}).votingAge||18)-18)*.03));
function gc(incs,seats,wv,lim,lo){const out=[];(incs||[]).forEach(o=>{if(!o)return;const ok=(o.terms||1)<lim&&(!lo||o.by==null||curY()-o.by>=lo);if(ok&&rnd()<.85)out.push({name:o.name,first:o.first,last:o.last,party:o.party,inc:1,w:wv[o.party]*(1.2+rnd()*.5)})});
 const extra=Math.max(seats+1-out.length,seats==1?1+Math.floor(rnd()*3):Math.ceil(seats*.5)+1);for(let i=0;i<extra;i++){const p=sample(wv),n=cName(p);out.push({...n,party:p,w:wv[p]*(.5+rnd())})}return out}
function planRaces(){const P=S.parties,Y=yr(),presYr=S.lastPresY==null||Y-S.lastPresY>=S.con.presTerm,nw=natW(),lg=S.con.lguLimit,wv=e=>wt(e,-1);
 const F={Y,pres:presYr,pub:false,P:P.map(p=>({name:p.name,color:p.color,acr:p.acr||''})),nat:{},prov:{},mun:{}};
 if(presYr){const inc=S.con.presReelect>=S.pres.terms;F.nat.pres=P.map((p,i)=>({...(inc&&i==S.pres.party?{name:S.pres.name,first:S.pres.first,last:S.pres.last,inc:1}:cName(i)),party:i,w:nw[i]*(.8+rnd()*.4)}));F.nat.vp=P.map((p,i)=>({...cName(i),party:i,w:nw[i]*(.8+rnd()*.4)}))}
 const full=S.con.senTerm<=S.con.houseTerm,c=S.elections.length%2,slots=[];S.senate.forEach((s,i)=>{if(full||s.cls==c)slots.push(i)});const n=slots.length,per=Math.max(4,Math.ceil(n/2)),sc=[];
 P.forEach((p,pi)=>{for(let k=0;k<per;k++)sc.push({...cName(pi),party:pi,w:nw[pi]*(.4+rnd()*1.2)})});slots.forEach(i=>{const s=S.senate[i];if((s.terms||1)<S.con.senLimit)sc.push({name:s.name,first:s.first,last:s.last,party:s.party,inc:1,w:nw[s.party]*(.8+rnd()*1.2),slot:i})});
 F.nat.sen={seats:n,slots,c:sc};F.nat.pl=S.plg.map(g=>{ensureNominees(g,5);return{name:g.name,kind:g.kind,party:g.party,nominees:g.nominees.map(x=>x.name)}});
 S.provs.forEach(p=>{const w=wv(p),e={name:p.name,reg:p.reg,gov:gc([p.gov],1,w,lg,23),vg:gc([p.vg],1,w,lg,23),sp:[],hr:[]};(p.pds||[]).forEach(d=>{const inc=p.sp.filter(o=>o.pd==d.n);if(inc.length)e.sp.push({pd:d.n,seats:inc.length,c:gc(inc,inc.length,w,lg,18)})});
  (p.districts||[]).forEach(d=>{const r=S.house.find(h=>h.prov==p.id&&h.d==d.n);e.hr.push({d:d.n,munis:d.munis.map(i=>S.munis[i]?S.munis[i].name:''),c:gc([r],1,w,S.con.houseLimit,25)})});F.prov[p.id]=e});
 S.munis.forEach(m=>{const w=wv(m);F.mun[m.id]={name:m.name,prov:m.prov,huc:m.huc,icc:m.icc,city:m.city,my:gc([m.mayor],1,w,lg,m.city?23:21),vm:gc([m.vm],1,w,lg,m.city?23:21),sb:{seats:m.sb.length,c:gc(m.sb,m.sb.length,w,lg,18)}}});
 S.cands=F;return F}
const FEMS=typeof FEM!='undefined'?FEM:new Set();
function elect(){if(!S.cands||S.cands.Y!=yr())planRaces();const F=S.cands,P=S.parties,Y=yr(),presYr=F.pres,pend={provs:[],munis:[],house:[],senate:[],pres:null,vp:null},nw=natW();
 const mreg=S.munis.map(m=>regV(m.pop)),mbal=mreg.map(r=>Math.round(r*cl(.77+(rnd()-.5)*.12,.55,.93))),mval=mbal.map(b=>Math.round(b*.97)),sum=(ids,A)=>ids.reduce((s,i)=>s+A[i],0);
 const valP=S.provs.map(p=>sum(p.mun,mval)),nat={reg:mreg.reduce((a,b)=>a+b,0),bal:mbal.reduce((a,b)=>a+b,0),val:mval.reduce((a,b)=>a+b,0)};F.nat.reg=nat.reg;F.nat.bal=nat.bal;F.nat.val=nat.val;
 const R={id:S.elections.length+1,d:dstr(),pres:presYr,P:F.P,reg:nat.reg,ballots:nat.bal,valid:nat.val,gov:z(),vg:z(),sp:z(),my:z(),cc:z(),mc:z(),huc:z(),govRows:[],houseRows:[],hucRows:[]};
 const run=(cands,seats,total)=>{const v=alloc(Math.round(total*(seats>1?seats*.85:1)),norm(cands.map(c=>c.w)));cands.forEach((c,i)=>{c.votes=v[i];c.ix=i});cands.sort((a,b)=>b.votes-a.votes);cands.forEach((c,i)=>{c.won=i<seats?1:0;delete c.w});return cands.slice(0,seats)};
 const off=(x,hold,lo)=>{const h=(hold||[]).find(o=>o&&o.name==x.name);if(x.inc&&h){h.terms=(h.terms||1)+1;return h}return{name:x.name,first:x.first,last:x.last,party:x.party,terms:1,by:curY()-(lo+Math.floor(rnd()*30)),sex:FEMS.has(x.first)?'F':'M',occ:pick(OCC)}};
 const matrix=(cands,k)=>{const pv=[],tot=cands.map(()=>0);S.provs.forEach(p=>{const wn=norm(wt(p,-1)),w=cands.map(c=>c.w*((wn[c.party]/(nw[c.party]||1))||1)),v=alloc(Math.round(valP[p.id]*k),norm(w));v.forEach((x,i)=>tot[i]+=x);pv.push(v)});cands.forEach((c,i)=>{c.votes=tot[i];c.ix=i});cands.sort((a,b)=>b.votes-a.votes);return pv};
 S.provs.forEach(p=>{const e=F.prov[p.id]||{},elig=p.mun.filter(id=>!(S.munis[id].huc||S.munis[id].icc)),vg0=sum(elig,mval);
  const gw=run(e.gov,1,vg0)[0],vw=run(e.vg,1,vg0)[0],gov=off(gw,[p.gov],23),vg=off(vw,[p.vg],23),sp=[];
  (e.sp||[]).forEach(r=>{const pds=(p.pds||[]).find(d=>d.n==r.pd),val=pds?sum(pds.munis,mval):vg0;run(r.c,r.seats,val).forEach(x=>{const o=off(x,p.sp,18);o.pd=r.pd;sp.push(o)});r.valid=val});
  while(sp.length<p.sp.length)sp.push({...person(p.lean,18),pd:1});sp.length=Math.max(1,p.sp.length);
  e.reg=sum(p.mun,mreg);e.bal=sum(p.mun,mbal);e.val=valP[p.id];e.elect=vg0;e.name=p.name;pend.provs.push({gov,vg,sp});R.gov[gov.party]++;R.vg[vg.party]++;sp.forEach(o=>R.sp[o.party]++);R.govRows.push({loc:p.name,name:gov.name,party:gov.party,votes:gw.votes,valid:vg0})});
 S.munis.forEach(m=>{const e=F.mun[m.id]||{},k=m.huc?'huc':m.city?'cc':'mc',val=mval[m.id],mw=run(e.my,1,val)[0],vm=run(e.vm,1,val)[0],mayor=off(mw,[m.mayor],m.city?23:21),vv=off(vm,[m.vm],m.city?23:21),sb=run(e.sb.c,e.sb.seats,val).map(x=>off(x,m.sb,18));
  while(sb.length<m.sb.length)sb.push(person(m.lean,18));e.reg=mreg[m.id];e.bal=mbal[m.id];e.val=val;pend.munis.push({mayor,vm:vv,sb});R.my[mayor.party]++;sb.forEach(o=>R[k][o.party]++);if(m.huc)R.hucRows.push({loc:m.name+' (HUC)',name:mayor.name,party:mayor.party,votes:mw.votes,valid:val})});
 const hc=z(),hi={};S.house.forEach((r,i)=>{if(r.prov>=0)hi[r.prov+':'+r.d]=i});
 S.provs.forEach(p=>{const e=F.prov[p.id]||{};(e.hr||[]).forEach(hr=>{const d=(p.districts||[]).find(x=>x.n==hr.d),val=d?sum(d.munis,mval):valP[p.id],reg=d?sum(d.munis,mreg):0,w=run(hr.c,1,val)[0],i=hi[p.id+':'+hr.d],r=S.house[i];hr.reg=reg;hr.val=val;
  const f=w.inc&&r&&r.name==w.name?(r.terms=(r.terms||1)+1,r):{...mem(w.party,P,25,true),name:w.name,first:w.first,last:w.last,prov:p.id,d:hr.d};if(i!=null)pend.house.push([i,f]);hc[f.party]++;R.houseRows.push({loc:`${p.name}, District ${hr.d}`,name:f.name,party:f.party,votes:w.votes,valid:val,reg})})});
 S.plg.forEach(g=>g.pop=+Math.max(.01,g.pop*(.8+rnd()*.4)).toFixed(3));
 const base=S.plg.map(g=>g.pop*(.85+rnd()*.3)),plv=S.plg.map(()=>0),plpv=[];S.provs.forEach(p=>{const v=alloc(valP[p.id],norm(S.plg.map((g,i)=>base[i]*(g.kind=='regional'?(g.region==p.reg?2.5:.4):1))));v.forEach((x,i)=>plv[i]+=x);plpv.push(v)});
 const plw=norm(plv),dcount=S.house.filter(r=>r.prov>=0).length;pend.pls=plSeats(S,Math.floor(dcount*S.con.plShare/(100-S.con.plShare)),plw);pend.pls.forEach((n,i)=>hc[S.plg[i].party>=0?S.plg[i].party:(S.plg[i].bloc||0)]+=n);
 const slots=F.nat.sen.slots,n=slots.length,sc=F.nat.sen.c,spv=matrix(sc,n*.9);
 const nsc=S.senate.slice(),sen=[];sc.slice(0,n).forEach((x,k)=>{const i=slots[k],h=x.inc?S.senate[x.slot]:null,m=h||Object.assign(mem(x.party,P,35,true),{name:x.name,first:x.first,last:x.last});if(h)m.terms=(m.terms||1)+1;const nn=Object.assign(m,{cls:S.senate[i].cls});pend.senate.push([i,nn]);nsc[i]=nn;sen.push({name:nn.name,party:nn.party});x.won=1});sc.forEach((x,k)=>{if(k>=n)x.won=0;delete x.w});R.sen=sen;
 R.senRace=sc.slice(0,n+6).map((x,k)=>({name:x.name,first:x.first,last:x.last,party:x.party,votes:x.votes,won:k<n}));F.nat.sen.pv=spv;
 if(presYr){const pp=matrix(F.nat.pres,1),inc=S.con.presReelect>=S.pres.terms,cs=F.nat.pres,vp=matrix(F.nat.vp,1),vc=F.nat.vp,w=cs[0],w2=vc[0];F.nat.presPv=pp;F.nat.vpPv=vp;
  cs.forEach((c,i)=>{c.won=i==0?1:0;delete c.w});vc.forEach((c,i)=>{c.won=i==0?1:0;delete c.w});R.cands=cs.map(c=>({...c}));R.win=0;R.vc=vc.map(c=>({...c}));R.vwin=0;R.vpw=R.vc[0];
  if(w.inc&&w.name==S.pres.name){S.pres.terms++;pend.pres=S.pres}else pend.pres=Object.assign(mem(w.party,P,40,true),{name:w.name,first:w.first,last:w.last});pend.vp=Object.assign(mem(w2.party,P,40,true),{name:w2.name,first:w2.first,last:w2.last});S.lastPresY=Y}
 F.nat.pl=S.plg.map((g,i)=>{ensureNominees(g,pend.pls[i]);return{name:g.name,kind:g.kind,party:g.party,nominees:g.nominees.map(x=>x.name),votes:plv[i],seats:pend.pls[i]}});F.nat.plPv=plpv;
 R.house=hc;R.senAll=tally(nsc).slice(0,P.length);R.pl=S.plg.map((g,i)=>({name:g.name,kind:g.kind,party:g.party,n:pend.pls[i],votes:plv[i],pct:plw[i]*100,seated:g.nominees.slice(0,pend.pls[i]).map(x=>x.name)}));
 F.pub=true;F.done=true;R.F=F;R.label=`${Y} ${presYr?'Presidential':'Midterm'} and Local Election`;S.elections.unshift(R);S.pend=pend;S.cands=null;
 S.inaug=dn(Y,5,30,S.y0);S.convene=openDay(Y,S.y0);S.next=elecDay(Y+S.con.houseTerm,S.y0);S.lastLocal=S.inaug;buildCal();
 log(presYr?`${pend.pres.name} of ${P[pend.pres.party].name} wins the presidency. Winners take office on June 30.`:'Midterm results are in. Winners take office on June 30.')}
function buildCal(){const E=S.next,B=S.nextB,ev=[],a=(d,key,label,basis)=>ev.push({d,key,label,basis});
 a(E-220,'file_open','Filing of certificates of candidacy opens (period fixed by COMELEC)','Sec. 7; Sec. 75');a(E-213,'file_close','Filing of certificates of candidacy closes; the lists of candidates are prepared','Sec. 75; Sec. 76');
 a(E-195,'petitions','Last day to petition to deny due course or cancel a certificate of candidacy (25 days after filing)','Sec. 78');a(E-185,'tentative','COMELEC publishes the tentative list of candidates','Sec. 7');
 a(E-135,'conv_nat','Party conventions for national positions may begin (within 45 days before the campaign period)','Sec. 80');a(E-130,'bft','The ballot face template for each locality is approved','Sec. 7');
 a(E-120,'cert','The certified list of candidates is finalized','Sec. 7');a(E-110,'print','Ballot printing begins','Sec. 7');
 a(E-90,'camp_nat','Election period begins; the campaign for President, Vice President, Senators, and party-list begins','Sec. 3; RA 7166 Sec. 5');a(E-75,'conv_loc','Party conventions for local positions may begin (within 30 days before the campaign period)','Sec. 80');
 a(E-45,'camp_loc','The campaign for House members and local officials begins','Sec. 3; RA 7166 Sec. 5');a(E-15,'disq1','Petitions to deny due course must be decided at least 15 days before election day','Sec. 78');
 a(E-10,'ballots','The number of ballots printed is published; statements of contributions and expenses may be filed (10 to 7 days before)','Sec. 59; Sec. 107');a(E-7,'disq2','Disqualification cases must be decided at least 7 days before election day; statements of contributions and expenses are due','Sec. 72; Sec. 107');
 a(E-1,'eve','The campaign ends; giving transportation, food, or drink is prohibited on the eve and on election day','Sec. 3; Sec. 89');a(E,'eday','Election day; canvass begins by 6 p.m.','Sec. 15; RA 7166 Sec. 3');
 a(E+3,'proc','Boards of canvassers proclaim the local winners','Omnibus Election Code, canvass provisions');a(E+14,'cong','Congress canvasses the presidential and vice-presidential votes (no later than 30 days after election day)','Sec. 16; Art. VII Sec. 4');
 a(E+30,'soce','The election period ends; supplemental statements of contributions and expenses and contributor reports are due','Sec. 3; Sec. 99; Sec. 107');a(E+180,'oath','Winners must take their oath within six months of proclamation','Sec. 11');
 a(B-90,'b_period','The election period for the barangay and SK elections begins','Sec. 3');a(B-60,'b_file_open','Filing of certificates of candidacy for barangay posts opens (period fixed by COMELEC)','Sec. 39; Sec. 7');a(B-53,'b_file_close','Filing for barangay posts closes','Sec. 39');
 a(B-15,'b_camp','The barangay campaign period begins','Sec. 3');a(B-10,'b_list','The consolidated list of candidates is posted and the board of election tellers is constituted at least 10 days before the election','Sec. 39; Sec. 40');a(B-7,'b_canv','The board of canvassers is constituted at least 7 days before the election','Sec. 46');a(B,'b_day','Barangay and SK election day (second Monday of November)','RA 12326');
 ev.sort((x,y)=>x.d-y.d);S.cal={E,B,ev};catchCal()}
function catchCal(){if(!S.cal)return;S.cal.ev.forEach(e=>{if(e.d<S.dt)e.done=1});const fc=S.cal.ev.find(e=>e.key=='file_close'),tn=S.cal.ev.find(e=>e.key=='tentative');if(fc&&fc.d<=S.dt&&(!S.cands||S.cands.Y!=yr()))planRaces();if(tn&&tn.d<=S.dt&&S.cands)S.cands.pub=true;const bf=S.cal.ev.find(e=>e.key=='bft');if(bf&&bf.d<=S.dt&&S.cands)S.cands.bft=true}
function calTick(){if(!S.cal||S.cal.E!=S.next||S.cal.B!=S.nextB)buildCal();S.cal.ev.forEach(e=>{if(e.d==S.dt&&!e.done){e.done=1;log('COMELEC calendar: '+e.label+'.');if(e.key=='file_close')planRaces();if(e.key=='tentative'&&S.cands)S.cands.pub=true;if(e.key=='bft'&&S.cands)S.cands.bft=true}})}
function inaugurate(){const p=S.pend;if(!p)return;
 p.provs.forEach((x,i)=>{const o=S.provs[i];if(o){Object.assign(o,x);hist(o,x.gov)}});p.munis.forEach((x,i)=>{const o=S.munis[i];if(o){Object.assign(o,x);hist(o,x.mayor)}});
 p.house.forEach(([i,n])=>{if(S.house[i]&&S.house[i].prov>=0)S.house[i]=n});p.senate.forEach(([i,n])=>{if(S.senate[i])S.senate[i]=n});rebuildPL(S,p.pls);
 if(p.pres){S.pres=p.pres;S.vp=p.vp;S.stats.approval=58}
 Object.keys(S.autos).forEach(r=>autoElect(S,+r));S.pend=null;S.inaug=null;tribunals();log(p.pres?`${S.pres.name} is inaugurated as President. Newly elected local officials take office.`:'Newly elected officials take office.')}
function openSession(){log('Congress opens its regular session (Art. VI Sec. 15). The President delivers the State of the Nation Address.');if(S.convene!=null&&S.dt>=S.convene){S.convene=null;rebuildCmt();electSpeaker();electSenPres()}}
function migrate(s){if(s.cands===undefined)s.cands=null;s.enacted=s.enacted||[];s.raNext=s.raNext||12500;initExtras(s);if(s.barmm&&!s.autos){s.autos={5:s.barmm};delete s.barmm}s.autos=s.autos||{};['pend','inaug','convene'].forEach(k=>{if(s[k]===undefined)s[k]=null});if(s.next==null)s.next=elecDay(s.y0,s.y0);s.plebs=s.plebs||[];if(s.ml===undefined)s.ml=null;if(s.senPres==null)s.senPres=0;if(s.flagSd==null)s.flagSd=hash('flag'+s.seed);s.justices.forEach(j=>{if(j.age==null)j.age=55+Math.floor(Math.random()*15)});s.bodies.forEach(b=>{if(b.since==null)b.since=s.y0-Math.floor(Math.random()*7)});return s}
function bske(){const P=S.parties,Y=yr(),R={id:S.elections.length+1,d:dstr(),bske:true,P:P.map(p=>({name:p.name,color:p.color})),pb:z(),kg:z(),sk:z()};
 S.munis.forEach(m=>m.brgy.forEach(b=>{const w=wt(m,-1),l=S.rules.brgyLimit;b.pb=re(b.pb,w,l);b.kag=b.kag.map(o=>re(o,w,l));b.sk=re(b.sk,w,S.rules.skLimit);R.pb[b.pb.party]++;b.kag.forEach(o=>R.kg[o.party]++);R.sk[b.sk.party]++}));
 R.label=`${Y} Barangay and SK Elections`;S.elections.unshift(R);S.nextB=bskeDay(Y+S.rules.brgyTerm,S.y0);log(`Barangay and Sangguniang Kabataan elections are held nationwide. Terms run ${S.rules.brgyTerm} years (RA 12326).`)}
function monthly(){const s=S.stats;applyBudget(s);LAWS.forEach(l=>{if(S.laws[l[0]]!==false)for(const k in l[6])s[k]=(s[k]||0)+l[6][k]});s.treasury=+(s.treasury+(s.growth-4)*.03).toFixed(2);s.approval+=(rnd()-.5)*2+(s.growth-4)*.15-(s.corruption-40)*.01;s.growth+=(5-s.growth)*.08+(rnd()-.5)*.3;s.corruption+=(rnd()-.5)*1.2;s.order+=(68-s.order)*.05+(rnd()-.5);
 s.poverty+=(rnd()-.52)*.3-(s.growth-4)*.05;['education','health','environment'].forEach(k=>s[k]+=(rnd()-.48)*.4);
 for(const k in s)s[k]=+cl(s[k],k=='treasury'||k=='growth'?-20:0,k=='treasury'?999:k=='growth'?20:100).toFixed(2)}

const clsOf=pop=>pop>1.7e6?1:pop>1.1e6?2:pop>7e5?3:pop>4e5?4:pop>2.2e5?5:6,distOf=pop=>Math.max(1,Math.min(8,Math.round(pop/290000)));
const cellsOf=ids=>{const t=new Set(ids),M=S.map;let n=0;for(let i=0;i<W*H;i++)if(M.mun[i]>=0&&t.has(M.mun[i]))n++;return n};
function provCheck(ids){const ms=ids.map(i=>S.munis[i]),pop=ms.reduce((a,m)=>a+m.pop,0),area=cellsOf(ids)*10,inc=Math.round(pop*220/1e5)/10,notes=[],from=[...new Set(ms.map(m=>m.prov))];
 if(!(pop>=250000||area>=2000))notes.push(`A province needs 250,000 residents or 2,000 sq km (this has ${fmt(pop)} and ${fmt(area)}). LGC Sec. 461.`);
 if(inc<20)notes.push(`A province needs PHP 20 million in annual income (estimated ${inc} million).`);
 from.forEach(pi=>{const p=S.provs[pi],rest=p.mun.filter(id=>!ids.includes(id));if(!rest.length)return;const rp=rest.reduce((a,id)=>a+S.munis[id].pop,0);if(!(rp>=250000||cellsOf(rest)*10>=2000))notes.push(`${p.name} would fall below the minimum (${fmt(rp)} residents) after the split.`)});
 return{pop,area,inc,notes,ok:!notes.length,from}}
function proposeProvince(ids,name,ov){if(S.pend)return'Wait until the newly elected officials take office.';const c=provCheck(ids),emptied=c.from.filter(pi=>S.provs[pi].mun.every(id=>ids.includes(id))).length;if(S.provs.length-emptied>=MAX_PROVINCES)return`The simulation allows at most ${MAX_PROVINCES} provinces.`;if(!c.ok&&!ov)return c.notes.join(' ');
 const d=S.dt+60+Math.floor(rnd()*31);S.plebs.push({kind:'prov',ids:ids.slice(),name,d});log(`A plebiscite on creating ${name} Province is set for ${fday(d)} in the affected municipalities (Art. X Sec. 10).`);return''}
function dropProv(k){S.provs.splice(k,1);S.provs.forEach((p,i)=>p.id=i);const M=S.map;for(let i=0;i<W*H;i++){if(M.prov[i]>k)M.prov[i]--;else if(M.prov[i]==k)M.prov[i]=-1}S.munis.forEach(m=>{if(m.prov>k)m.prov--});S.house=S.house.filter(r=>r.prov!=k);S.house.forEach(r=>{if(r.prov>k)r.prov--})}
function createProvince(ids,name){const ms=ids.map(i=>S.munis[i]),pop=ms.reduce((a,m)=>a+m.pop,0),from=[...new Set(ms.map(m=>m.prov))],id=S.provs.length,ln=norm(S.parties.map((_,k)=>ms.reduce((a,m)=>a+m.lean[k]*m.pop,0)+1e-6)),M=S.map,t=new Set(ids);
 let sx=0,sy=0,n=0;for(let i=0;i<W*H;i++)if(M.mun[i]>=0&&t.has(M.mun[i])){sx+=i%W;sy+=i/W|0;n++}
 const cls=clsOf(pop),dist=distOf(pop),p={id,name,pop,cls,dist,reg:S.provs[ms[0].prov].reg,cx:Math.round(sx/Math.max(1,n)),cy:Math.round(sy/Math.max(1,n)),lean:ln,mun:[],hist:[]};
 p.gov=person(ln);p.vg=person(ln);p.sp=Array.from({length:dist>5?dist*2:cls<3?10:cls<5?8:6},()=>person(ln));p.exo=exo().concat([{name:nm(),party:-1,role:'League of Cities Council Presidents'},{name:nm(),party:-1,role:'League of Municipal Councilors President'}]);
 from.forEach(pi=>{const q=S.provs[pi];q.pop=Math.max(20000,q.pop-ms.filter(m=>m.prov==pi).reduce((a,m)=>a+m.pop,0));q.cls=clsOf(q.pop);q.dist=distOf(q.pop)});
 S.provs.push(p);ms.forEach(m=>m.prov=id);p.distStatus='enacted';p.dev=50;p.ie=+(.6+rnd()*.9).toFixed(2);reclassOne(p,'province');syncGeo();for(let k=S.provs.length-2;k>=0;k--)if(!S.provs[k].mun.length)dropProv(k);syncGeo();
 if(typeof sel!='undefined')sel={p:-1,m:-1};log(`${name} Province is created from ${ms.length} municipalities with ${fmt(pop)} residents.`)}
function plebs(){S.plebs=S.plebs.filter(p=>{if(S.dt<p.d)return true;const y=52+(S.stats.approval-50)*.3+(rnd()-.5)*20;
 if(p.kind=='prov'){log(`Plebiscite on ${p.name} Province: ${y.toFixed(1)}% yes.`);if(y>50&&!S.pend&&p.ids.every(i=>S.munis[i]))createProvince(p.ids,p.name);else log(`${p.name} Province is not created.`)}
 else if(p.kind=='auto'){log(`Plebiscite on autonomy for ${S.regs[p.reg].name}: ${y.toFixed(1)}% yes.`);if(y>50){S.regs[p.reg].auto=true;autoElect(S,p.reg);log(`${S.regs[p.reg].name} becomes an autonomous region (Art. X Sec. 18).`)}else log('Autonomy is rejected.')}else if(p.kind=='op'){log(`Plebiscite on ${p.label}: ${y.toFixed(1)}% yes.`);if(y>50&&!S.pend){const r=OPS[p.op](p.args);if(r)log('The result cannot be carried out: '+r)}else log('The proposal is rejected.')}else if(p.kind=='mmerge'){log(`Plebiscite on merging municipalities into ${p.name}: ${y.toFixed(1)}% yes.`);if(y>50&&!S.pend&&p.ids.every(i=>S.munis[i]))mergeMunis(p.ids,p.name);else log('The merger is rejected.')}
 return false})}
function tribunals(){const d=S.house.filter(r=>r.prov>=0).length,n=Math.max(1,Math.round(d*.05));let up=0,ov=0;for(let k=0;k<n;k++){const i=Math.floor(rnd()*S.house.length),r=S.house[i];if(!r||r.prov<0)continue;if(rnd()<.2){ov++;S.house[i]={...mem(sample(S.parties.map((_,j)=>j==r.party?0:1)),S.parties),prov:r.prov,d:r.d}}else up++}
 log(`The House Electoral Tribunal (3 Justices and 6 members, Art. VI Sec. 17) rules on ${up+ov} election protests: ${up} upheld, ${ov} overturned.`)}
function caVote(){const sen=S.senate.filter((_,i)=>i%2==0).slice(0,12),st=Math.max(1,Math.floor(S.house.length/12)),hs=S.house.filter((_,i)=>i%st==0).slice(0,12);return ballot(sen.concat(hs),{i:S.pres.ideo,tags:[],e:{},spp:S.pres.party,mine:false},null,false)}
function caConfirm(name,role){const r=caVote(),sp=S.senate[S.senPres];return `The Commission on Appointments${sp?' (chaired by Senate President '+sp.name+')':''} ${r.pass?'confirms':'bypasses'} ${name}${role?', '+role:''}: ${r.y} yes, ${r.n} no.`}
function electSenPres(){const L=S.senate,cands=S.parties.map((p,i)=>{let b=-1,bt=-1;L.forEach((m,j)=>{if(m.party==i&&(m.terms||1)*10+m.integ>bt){bt=(m.terms||1)*10+m.integ;b=j}});return b}).filter(j=>j>=0),t=cands.map(()=>0);
 L.forEach(m=>{let bi=0,bs=-9;cands.forEach((j,k)=>{const c=L[j],s=(m.party==c.party?.9*m.loyal+.3:0)-Math.abs(m.ideo-c.ideo)*.8+(rnd()-.5)*.3;if(s>bs){bs=s;bi=k}});t[bi]++});S.senPres=cands[t.indexOf(Math.max(...t))];log(`${L[S.senPres].name} is elected Senate President (${t.join(', ')} votes).`);leaders()}
function nominateVP(){let c;for(let k=0;k<3;k++){c=mem(sample(natW()),S.parties);const b={i:c.ideo,tags:[],e:{},spp:S.pres.party,mine:false},h=ballot(S.house,b,null,false,.5),s=ballot(S.senate,b,null,false,.5);if(h.pass&&s.pass){log(`${c.name} is nominated Vice President and confirmed by both Houses voting separately (Art. VII Sec. 9).`);return c}}log('Congress does not confirm the nominees. The last nominee serves until confirmed.');return c}
const jointVote=(f)=>{const all=S.house.concat(S.senate);return{y:all.filter(f).length,n:all.length}};
function martial(){if(S.ml)return;S.ml={d:S.dt,end:S.dt+60};S.stats.order=cl(S.stats.order+8,0,100);S.stats.approval=cl(S.stats.approval-6,0,100);log(`${S.pres.name} proclaims martial law for 60 days (Art. VII Sec. 18). Congress reviews the proclamation in joint session.`);
 const r=jointVote(m=>(m.party!=S.pres.party?.3:-.5)+(m.integ-.5)*.4-(S.stats.order-55)/120+(rnd()-.5)*.3>.1);log(`Joint vote on revocation: ${r.y} of ${r.n} vote to revoke; a majority of all members is needed.`);
 if(r.y>r.n/2){log('Congress revokes the proclamation. The President cannot set the revocation aside.');S.ml=null;return}
 if(rnd()<.3){log('The Supreme Court finds no sufficient factual basis and nullifies the proclamation.');S.ml=null}}
function extendML(){if(!S.ml)return;const r=jointVote(m=>(m.party==S.pres.party?.3:-.4)-(m.integ-.5)*.3+(rnd()-.5)*.3>.1);log(`Joint vote to extend martial law: ${r.y} of ${r.n} yes.`);if(r.y>r.n/2){S.ml.end+=60;log('Congress extends martial law for 60 days.')}else log('The extension is not approved.')}
function revokeML(){if(!S.ml)return;const r=jointVote(m=>(m.party!=S.pres.party?.3:-.5)+(m.integ-.5)*.4+(rnd()-.5)*.3>.1);log(`Joint vote to revoke martial law: ${r.y} of ${r.n} yes.`);if(r.y>r.n/2){log('Congress revokes martial law.');S.ml=null}else log('The motion to revoke fails.')}
function gaaDraft(force){const Y=yr()+1;let t=`General Appropriations Act of FY ${Y}`;if(S.bills.some(b=>b.t==t&&STN[b.st]))return;if(S.bills.some(b=>b.t==t)){if(!force)return;t=`Supplemental Appropriations Act of FY ${Y}`}
 const arts=S.budget.lines.map(l=>({id:0,t:`${l.name}: ${l.nep} billion`,i:l.i||0,tags:['budget',l.tag].filter(Boolean),e:{},bud:{id:l.id,amt:l.nep}}));
 const b=makeBill({title:t,arts,orig:'H',sp:{ch:'H',i:Math.floor(rnd()*S.house.length)}});S.budget.fy=Y;log(`The President submits the National Expenditure Program. ${b.spn} files the ${t} in the House (Art. VII Sec. 22).`)}
function budgetCheck(){const t=`General Appropriations Act of FY ${yr()}`,b=S.bills.find(x=>x.t==t);if(b&&b.st=='Law')return;S.stats.growth=cl(S.stats.growth-.2,-20,20);S.stats.approval=cl(S.stats.approval-1,0,100);log(`Congress did not pass the ${t}. The previous appropriations are re-enacted (Art. VI Sec. 25).`)}
function yearly(){incomeYearly();S.justices.forEach(j=>{j.age=(j.age||60)+1;if(j.age>=70){const o=j.name;j.name=nm();j.age=48+Math.floor(rnd()*10);j.lean=+(rnd()*2-1).toFixed(1);log(`Justice ${o} reaches the mandatory retirement age of 70 (Art. VIII Sec. 11). The President appoints ${j.name} from the Judicial and Bar Council's list.`)}});
 S.bodies.forEach(b=>{if(yr()-(b.since||S.y0)>=7){const o=b.name;b.name=nm();b.since=yr();log(`${o}'s seven-year term ends at ${b.role}. ${caConfirm(b.name,b.role)}`)}})}
function tick(){S.dt++;const sit0=()=>inSession();const dd=D(),mo=dd.getUTCMonth(),dm=dd.getUTCDate();
 S.bills.forEach(b=>{if(b.mine)return;if(STN[b.st]&&rnd()<.04)act(b,false,true);else if(b.st=='Vetoed'&&!b.ov&&rnd()<.05)act(b,false,true)});
 if(rnd()<.012)draft();if(rnd()<.015)log(pick(E)[1](S));
 if(S.crisis>0){S.crisis--;S.house.concat(S.senate).forEach(m=>m.trust=cl(m.trust-(m.party==S.player.party?.02:.05),0,100))}
 if(S.ml){S.stats.approval=cl(S.stats.approval-.03,0,100);if(S.dt>=S.ml.end){log('Martial law lapses after its 60-day limit (Art. VII Sec. 18).');S.ml=null}}
 if(dm==1)monthly();if(mo==0&&dm==1){budgetCheck();yearly()}if(mo==7&&dm==25)gaaDraft();
 plebs();S.ords.filter(o=>['Council','Executive','Vetoed','Review'].includes(o.st)).forEach(ordStep);if(rnd()<.05)ordAI();if(rnd()<.006&&sit0())localAI();
 calTick();if(S.dt==S.inaug)inaugurate();if(S.dt==openDay(yr(),S.y0))openSession();if(S.dt==S.next)elect();if(S.dt==S.nextB)bske();
 if(S.dt%60==0&&typeof autosave=='function')autosave()}

function applyBudget(s){const b=S.budget;if(!b)return;let sp=0;b.lines.forEach(l=>{sp+=l.amt;const r=l.amt/Math.max(1,l.base);for(const k in l.fx)s[k]=(s[k]||0)+l.fx[k]*(r-1)});const rv=b.rev*(1+(s.growth-5)/100),nta=rv*S.rules.ira/100;s.treasury+=(rv-sp-nta)/12/1000}
function localFx(a,k){k=k||1;if(a.fn&&k>0)a.fn.forEach(applyFn);if(a.reap!=null&&k>0){const p=S.provs[a.reap];if(p&&p.dprop){p.districts=p.dprop.map(d=>({n:d.n,munis:d.munis.slice()}));p.dist=p.districts.length;p.dprop=null;p.distStatus='enacted';syncGeo()}}if(a.loc!=null&&S.provs[a.loc]){const p=S.provs[a.loc];p.dev=cl((p.dev||50)+(a.dev||0)*k,0,100);if(k>0){p.laws=p.laws||[];p.laws.unshift(a.t);p.laws.length=Math.min(p.laws.length,6)}}
 if(a.bud){const l=S.budget.lines.find(x=>x.id==a.bud.id);if(l){if(k>0){a.bud.prev=l.amt;l.amt=a.bud.amt}else if(a.bud.prev!=null)l.amt=a.bud.prev}}
 if(a.st)S.laws[a.st.id]=k>0?a.st.on:!a.st.on}
function cName(pi){const[f,l]=takeName(S.parties[pi]);return{name:f+' '+l,first:f,last:l}}
function localBill(ri,t,title,mine){const r=S.house[ri];if(!r||r.prov<0)return null;const p=S.provs[r.prov],[tt,e,tag,i,dev]=LOCAL_LIB[t||0],txt=title||tt.replace('{p}',p.name);
 return makeBill({title:txt,arts:[{id:0,t:txt,i,tags:[tag,'local'],e:{...e},loc:p.id,dev}],orig:'H',sp:{ch:'H',i:ri},mine:!!mine})}
function localAI(){const ids=S.house.map((r,i)=>r.prov>=0?i:-1).filter(i=>i>=0);if(!ids.length)return;const ri=pick(ids),b=localBill(ri,Math.floor(rnd()*LOCAL_LIB.length));if(b)log(`${b.spn}, representative of ${S.provs[S.house[ri].prov].name}, files "${b.t}".`)}
const olog=(o,t)=>{o.log.unshift(`${dstr()}: ${t}`);o.log.length=Math.min(o.log.length,8)};
function ordInfo(o){if(o.lvl=='p'){const p=S.provs[o.ref];return p&&{mem:p.sp,exec:p.gov,name:p.name+' Sangguniang Panlalawigan',pop:p.pop,days:S.rules.vetoDays}}
 const m=S.munis[o.ref];if(!m)return null;if(o.lvl=='m')return{mem:m.sb,exec:m.mayor,name:m.name+(m.city?' Sangguniang Panlungsod':' Sangguniang Bayan'),pop:m.pop,days:S.rules.vetoDays};
 const b=m.brgy[o.bi];return b&&{mem:b.kag,exec:b.pb,name:'Sangguniang Barangay of '+b.name,pop:m.pop/Math.max(1,m.bn),days:Math.max(5,S.rules.vetoDays-5)}}
const ordReview=o=>o.lvl=='b'||(o.lvl=='m'&&!S.munis[o.ref].huc);
function ordEnact(o,c){const tp=S.provs.reduce((a,p)=>a+p.pop,0)||1,f=Math.min(1,c.pop/tp*4);for(const k in o.e)S.stats[k]=+cl((S.stats[k]||0)+o.e[k]*f,k=='treasury'||k=='growth'?-20:0,k=='treasury'?999:k=='growth'?20:100).toFixed(2);
 const e=o.lvl=='p'?S.provs[o.ref]:S.munis[o.ref];if(e)e.dev=cl((e.dev||50)+(o.dev||0),0,100);log(`The ${c.name} enacts the ordinance "${o.t}".`)}
function ordStep(o){const c=ordInfo(o);if(!c){o.st='Failed';return}const P=S.parties,near=m=>Math.abs((P[m.party]||{ideo:0}).ideo-o.i)<.9,vote=m=>rnd()<(near(m)?.82:.22);
 if(o.st=='Council'&&S.dt-o.d>=3){const pr=c.mem.filter(()=>rnd()<S.rules.attend),y=pr.filter(vote).length;if(pr.length<=c.mem.length/2)olog(o,'The council lacks a quorum (LGC Sec. 53).');else if(y>pr.length/2){o.st='Executive';o.d2=S.dt;olog(o,`The council passes the ordinance on third reading, ${y} to ${pr.length-y}.`)}else{o.st='Failed';olog(o,`The ordinance fails, ${y} to ${pr.length-y}.`)}}
 else if(o.st=='Executive'){const sign=near(c.exec)?rnd()<.9:rnd()<.5,go=sign&&rnd()<.35,lapse=S.dt-o.d2>=c.days;
  if(go||lapse){o.st=ordReview(o)?'Review':'Enacted';o.d3=S.dt;olog(o,lapse&&!go?'The executive does not act within the period; the ordinance is deemed approved (LGC Sec. 54).':'The executive signs the ordinance.');if(o.st=='Enacted')ordEnact(o,c)}
  else if(!sign&&rnd()<.3){o.st='Vetoed';olog(o,'The executive vetoes the ordinance.')}}
 else if(o.st=='Vetoed'&&!o.ov){o.ov=1;const y=c.mem.filter(vote).length;if(y>=c.mem.length*S.rules.overrideLocal/100){o.st=ordReview(o)?'Review':'Enacted';o.d3=S.dt;olog(o,`The council overrides the veto, ${y} of ${c.mem.length} (LGC Sec. 54).`);if(o.st=='Enacted')ordEnact(o,c)}else{o.st='Failed';olog(o,`The override fails, ${y} of ${c.mem.length}.`)}}
 else if(o.st=='Review'&&S.dt-o.d3>=S.rules.reviewDays){if(rnd()<.08){o.st='Failed';olog(o,'The reviewing council declares the ordinance invalid (LGC Sec. 56).')}else{o.st='Enacted';olog(o,'The review period lapses and the ordinance takes effect.');ordEnact(o,c)}}}
function ordFile(lvl,ref,bi,title,x,mine){const o={id:(S.ords.reduce((a,q)=>Math.max(a,q.id),0))+1,lvl,ref,bi,t:title,i:x.i,tags:x.tags,e:x.e,dev:x.dev||0,st:'Council',d:S.dt,log:[],mine:!!mine};S.ords.unshift(o);olog(o,'Filed and read on first reading.');if(S.ords.length>300)S.ords.length=300;return o}
function ordAI(){const r=rnd(),lvl=r<.5?'m':r<.8?'p':'b',[t,i,e,tags,dev]=pick(ORD_LIB);let ref,bi;if(lvl=='p')ref=Math.floor(rnd()*S.provs.length);else{ref=Math.floor(rnd()*S.munis.length);if(lvl=='b')bi=Math.floor(rnd()*S.munis[ref].brgy.length)}ordFile(lvl,ref,bi,t,{i,tags,e,dev})}
function leaders(){const P=S.parties.length,top=(L,party,ex)=>{let b=-1,bt=-1;L.forEach((m,j)=>{if(m.party==party&&j!=ex&&(m.terms||1)*10+m.integ>bt){bt=(m.terms||1)*10+m.integ;b=j}});return b},big=(L,ex)=>{const c=tally(L,P+1).slice(0,P);c[ex]=-1;return c.indexOf(Math.max(...c))},sp=S.house[S.speaker],sn=S.senate[S.senPres];S.floor={};
 if(sp){S.floor.hMaj=top(S.house,sp.party,S.speaker);S.floor.hMin=top(S.house,big(S.house,sp.party),-1)}if(sn){S.floor.sMaj=top(S.senate,sn.party,S.senPres);S.floor.sMin=top(S.senate,big(S.senate,sn.party),-1)}}
function fixDistricts(p){if(!p.districts||!p.districts.length){autoDist(p,p.mun.length?p.dist:null);return}p.districts.forEach(d=>d.munis=d.munis.filter(id=>S.munis[id]&&S.munis[id].prov==p.id));{const sn=new Set();p.districts.forEach(d=>d.munis=d.munis.filter(id=>!sn.has(id)&&sn.add(id)))}
 const have=new Set(p.districts.flatMap(d=>d.munis)),pop=d=>d.munis.reduce((a,i)=>a+S.munis[i].pop,0);p.mun.filter(id=>!have.has(id)).forEach(id=>{if(!p.districts.length)p.districts.push({n:1,munis:[]});p.districts.sort((a,b)=>pop(a)-pop(b))[0].munis.push(id)});
 p.districts=p.districts.filter(d=>d.munis.length);p.districts.forEach((d,i)=>d.n=i+1);if(p.districts.length&&p.dist!=p.districts.length)autoDist(p,p.dist)}
function fixCaps(){const big=ids=>ids.length?ids.reduce((b,id)=>S.munis[id].pop>S.munis[b].pop?id:b,ids[0]):null;S.provs.forEach(p=>{const c=p.capital;if(c==null||!S.munis[c]||S.munis[c].prov!=p.id)p.capital=big(p.mun)});
 S.regs.forEach((r,ri)=>{const ids=S.provs.filter(p=>p.reg==ri).flatMap(p=>p.mun);if(r.capital==null||!ids.includes(r.capital))r.capital=big(ids)});const n=S.nation.capital;if(n==null||!S.munis[n])capitals(S)}
function dropRegion(k){S.regs.splice(k,1);S.provs.forEach(p=>{if(p.reg>k)p.reg--});const na={};for(const r in S.autos){const i=+r;if(i!=k)na[i>k?i-1:i]=S.autos[r]}S.autos=na;S.plebs.forEach(p=>{if(p.reg!=null&&p.reg>k)p.reg--})}
function pruneRegions(){for(let k=S.regs.length-1;k>=0;k--)if(!S.provs.some(p=>p.reg==k))dropRegion(k)}
function setRegion(ids,ri){ids.forEach(id=>{S.provs[id].reg=ri});pruneRegions();fixCaps()}
function newRegion(name,ids){S.regs.push({name,auto:false,capital:null,rd:{name:nm(),party:-1}});const ri=S.regs.length-1;ids.forEach(id=>{S.provs[id].reg=ri});pruneRegions();fixCaps();log(`An executive order creates the region ${name} (Art. X Sec. 14).`);return ri}
function mergeRegions(a,b){if(a==b)return;const na=S.regs[a].name;S.provs.forEach(p=>{if(p.reg==b)p.reg=a});pruneRegions();fixCaps();log(`The region ${S.regs[b]?S.regs[b].name:''} is merged into ${na}.`)}
function dropMuni(k,into){const g=x=>x>k?x-1:x,f=id=>id==k?g(into):g(id),M=S.map;for(let i=0;i<W*H;i++)if(M.mun[i]==k)M.mun[i]=into;for(let i=0;i<W*H;i++)if(M.mun[i]>k)M.mun[i]--;
 S.munis.splice(k,1);S.munis.forEach((m,i)=>m.id=i);S.provs.forEach(p=>{(p.districts||[]).forEach(d=>d.munis=[...new Set(d.munis.map(f))]);if(p.capital!=null)p.capital=f(p.capital)});S.regs.forEach(r=>{if(r.capital!=null)r.capital=f(r.capital)});
 if(S.nation.capital!=null)S.nation.capital=f(S.nation.capital);S.ords.forEach(o=>{if(o.lvl!='p')o.ref=f(o.ref)});S.plebs.forEach(p=>{if(p.ids)p.ids=p.ids.map(f)})}
function proposeMerge(ids,name){if(S.pend)return'Wait until the newly elected officials take office.';if(ids.length<2)return'Select at least two municipalities.';if(new Set(ids.map(i=>S.munis[i].prov)).size>1)return'Municipalities must be in the same province to merge. Group them into a province first.';
 const d=S.dt+60+Math.floor(rnd()*31);S.plebs.push({kind:'mmerge',ids:ids.slice(),name,d});log(`A plebiscite on merging ${ids.length} municipalities into ${name} is set for ${fday(d)} (Art. X Sec. 10).`);return''}
function mergeMunis(ids,name){const ms=ids.map(i=>S.munis[i]).sort((a,b)=>b.pop-a.pop),base=ms[0],others=ms.slice(1).map(m=>m.id).sort((a,b)=>b-a);
 base.lean=norm(S.parties.map((_,k)=>ms.reduce((a,m)=>a+m.lean[k]*m.pop,0)+1e-6));base.pop=ms.reduce((a,m)=>a+m.pop,0);base.name=name;base.city=ms.some(m=>m.city);base.huc=base.city&&base.pop>=200000;reclassOne(base,lguType(base));base.brgy=base.brgy.slice();ms.slice(1).forEach(o=>{const off=base.brgy.length,M=S.map;for(let i=0;i<W*H;i++)if(M.mun[i]==o.id){M.mun[i]=base.id;M.bg[i]=M.bg[i]>=0?M.bg[i]+off:-1}base.brgy=base.brgy.concat(o.brgy)});base.bn=base.brgy.length;
 others.forEach(id=>dropMuni(id,S.munis.indexOf(base)));syncGeo();if(typeof grp!='undefined')grp=[];if(typeof sel!='undefined')sel={r:-1,p:-1,m:-1,b:-1};log(`${name} is formed by merging ${ms.length} municipalities, with ${fmt(base.pop)} residents.`)}

const INC_TABLE={province:[[1500,1],[900,2],[700,3],[500,4],[0,5]],city:[[1300,1],[1000,2],[800,3],[500,4],[0,5]],municipality:[[200,1],[160,2],[130,3],[90,4],[0,5]]};
const INC_PC={province:1.1,city:2.4,municipality:1.4},ORDN=['','1st','2nd','3rd','4th','5th'];
const INC_NOTE='RA 11964 (Automatic Income Classification of LGUs Act) and DOF Department Order 074-2024 set five classes based on three-year average regular income. Province boundaries below 900 million to 500 million and the 4th-class city floor are inferred from partial texts; the other limits were confirmed.';
const lguType=e=>e.city?'city':'municipality';
function incomeOf(e,type,s){s=s||S;return e.pop/1000*INC_PC[type]*(.7+(e.dev==null?50:e.dev)/100*.6)*(1+((s.stats&&s.stats.growth||5)-5)/50)*((s.rules&&s.rules.ira||40)/40)*(e.ie||1)}
const classOf5=(type,inc)=>INC_TABLE[type].find(r=>inc>=r[0])[1];
function reclassOne(e,type,s){s=s||S;e.incH=e.incH&&e.incH.length?e.incH:[incomeOf(e,type,s)];const avg=e.incH.reduce((a,b)=>a+b,0)/e.incH.length,c=classOf5(type,avg);
 e.ic={regularIncome:+avg.toFixed(1),incomeClass:ORDN[c]+' class '+type,cls:c,classificationYear:s.dt!=null?s.y0+Math.floor(s.dt/365.25):s.y0,legalBasisId:'RA 11964; DOF DO 074-2024',calculatedAutomatically:true};if(type=='province')e.cls=c}
function initIncome(s){[...s.provs.map(p=>[p,'province']),...s.munis.map(m=>[m,lguType(m)])].forEach(([e,t])=>{if(e.ie==null)e.ie=+(.6+rnd()*.9).toFixed(2);const v=incomeOf(e,t,s);e.incH=[v,v,v];reclassOne(e,t,s)});
 s.provs.forEach(p=>{const n=p.dist>5?p.dist*2:p.cls<3?10:p.cls<5?8:6;while(p.sp.length<n)p.sp.push(person(p.lean,18));p.sp.length=Math.min(p.sp.length,n)})}
function incomeYearly(){const gen=(yr()-S.y0)%3==0;[...S.provs.map(p=>[p,'province']),...S.munis.map(m=>[m,lguType(m)])].forEach(([e,t])=>{e.incH=(e.incH||[]).concat(incomeOf(e,t)).slice(-3);if(gen)reclassOne(e,t)});if(gen)log('The general income reclassification of provinces, cities, and municipalities takes effect (RA 11964).')}
function assignSP(p,s){s=s||S;const k=p.pds.length,tot=p.sp.length,pop=d=>d.munis.reduce((a,i)=>a+(s.munis[i]?s.munis[i].pop:0),0),order=p.pds.map((d,i)=>i).sort((a,b)=>pop(p.pds[b])-pop(p.pds[a])),n=p.pds.map(()=>Math.floor(tot/k));for(let r=tot-n.reduce((a,b)=>a+b,0),i=0;r>0;r--,i++)n[order[i%k]]++;
 let j=0;p.pds.forEach((d,di)=>{for(let c=0;c<n[di]&&j<tot;c++)p.sp[j++].pd=d.n})}
const eligPD=(s,id)=>s.munis[id]&&!(s.munis[id].huc||s.munis[id].icc);
function autoProv(p,s){s=s||S;const L=p.districts||[],el=p.mun.filter(id=>eligPD(s,id));let g=L.map(d=>d.munis.filter(id=>eligPD(s,id))).filter(x=>x.length);if(g.length<2)g=splitK(el,2,centroids(s),s);if(!g.length)g=[[]];
 p.pds=g.map((m,i)=>({n:i+1,munis:m,lds:L.length>=2?[(L[i]||{n:i+1}).n]:L.map(d=>d.n)}));p.pdAuto=true;if(p.sp.length)assignSP(p,s)}
function fixProvDistricts(p){if(!p.pds||!p.pds.length){autoProv(p);return}p.pds.forEach(d=>d.munis=d.munis.filter(id=>S.munis[id]&&S.munis[id].prov==p.id&&eligPD(S,id)));{const sn=new Set();p.pds.forEach(d=>d.munis=d.munis.filter(id=>!sn.has(id)&&sn.add(id)))}
 const have=new Set(p.pds.flatMap(d=>d.munis)),pop=d=>d.munis.reduce((a,i)=>a+S.munis[i].pop,0);p.mun.filter(id=>!have.has(id)&&eligPD(S,id)).forEach(id=>{p.pds.sort((a,b)=>pop(a)-pop(b))[0].munis.push(id)});
 p.pds=p.pds.filter(d=>d.munis.length);if(!p.pds.length){autoProv(p);return}p.pds.forEach((d,i)=>d.n=i+1);
 const nl=(p.districts||[]).filter(d=>d.munis.some(id=>eligPD(S,id))).length,want=nl>=2?nl:Math.min(2,p.mun.filter(id=>eligPD(S,id)).length||1);if(p.pdAuto&&p.pds.length!=want){autoProv(p);return}
 if(p.sp.some(m=>!p.pds.some(d=>d.n==m.pd)))assignSP(p)}
function proposeDist(p){const t={mun:p.mun.slice()};autoDist(t,null,S);p.dprop=t.districts.map(d=>({n:d.n,munis:d.munis.slice()}));return p.dprop}
function reapBill(p){if(!p.dprop)proposeDist(p);return makeBill({title:`Reapportionment of the legislative districts of ${p.name}`,arts:[{id:0,t:`Reapportion ${p.name} into ${p.dprop.length} legislative district(s)`,i:0,tags:['governance'],e:{},reap:p.id}],orig:'H',sp:{ch:'H',i:Math.max(0,S.house.findIndex(r=>r.prov==p.id))},mine:true})}
function validateWorld(){const e=[],add=m=>e.length<60&&e.push(m);if(S.provs.length>MAX_PROVINCES)add(`There are more than ${MAX_PROVINCES} provinces.`);
 S.provs.forEach((p,i)=>{if(p.id!==i)add(`Province ${p.name} has a stale id.`);if(!S.regs[p.reg])add(`${p.name} has no valid region.`);if(p.capital!=null&&(!S.munis[p.capital]||S.munis[p.capital].prov!==i))add(`The capital of ${p.name} is not in the province.`);
  [['legislative',p.districts],['provincial',p.pds]].forEach(([k,L])=>{const seen=new Set();(L||[]).forEach(d=>d.munis.forEach(id=>{if(!S.munis[id]||S.munis[id].prov!==i)add(`A ${k} district of ${p.name} lists a municipality outside the province.`);if(seen.has(id))add(`A municipality is in two ${k} districts of ${p.name}.`);seen.add(id)}));p.mun.forEach(id=>{if(!seen.has(id)&&(k=='legislative'||eligPD(S,id)))add(`${S.munis[id].name} is in no ${k} district of ${p.name}.`)})});
  const hs=S.house.filter(r=>r.prov===i).length;if(hs!==(p.districts||[]).length)add(`${p.name} has ${hs} House seats for ${(p.districts||[]).length} legislative districts.`);
  if(p.pdAuto&&(p.districts||[]).length==1&&p.pds.length<2&&p.mun.length>1)add(`${p.name} has one legislative district and should have two provincial districts.`);
  if(!p.ic)add(`${p.name} has no income classification.`)});
 S.munis.forEach((m,i)=>{if(m.id!==i)add(`${m.name} has a stale id.`);if(!S.provs[m.prov])add(`${m.name} has no province.`);if(!m.ic)add(`${m.name} has no income classification.`);if(m.brgy.some(b=>b.ic))add(`${m.name} has a barangay with an income class; barangays are never classified.`)});
 S.regs.forEach(r=>{if(r.capital!=null&&!S.munis[r.capital])add(`The capital of ${r.name} does not exist.`)});if(S.nation.capital!=null&&!S.munis[S.nation.capital])add('The national capital does not exist.');
 return e}
const provElectors=p=>Math.max(1,p.mun.reduce((a,id)=>{const m=S.munis[id];return a+(m&&!(m.huc||m.icc)?m.pop:0)},0));
function describeFn(f){if(f.t=='rule')return `Rule ${f.k} becomes ${f.v}`;if(f.t=='bud')return `NEP line ${f.line} ${f.pct>0?'+':''}${f.pct}%`;if(f.t=='dept')return f.add?`New department: ${f.add}`:`Department abolished: ${f.remove}`;if(f.t=='law')return `${(LAWS.find(l=>l[0]==f.id)||[0,'law'])[1]} ${f.on?'restored':'repealed'}`;if(f.t=='ie')return `Local income ${f.pct>0?'+':''}${f.pct}%`;return f.t}
function applyFn(f){if(f.t=='rule'&&RB[f.k]&&S.rules[f.k]!=null){const v=cl(+f.v,RB[f.k][0],RB[f.k][1]);S.rules[f.k]=v;log(`The simulation rule "${f.k}" is now ${v}.`)}
 else if(f.t=='bud'){const l=S.budget.lines.find(x=>x.id==f.line);if(l){l.nep=Math.max(1,Math.round(l.nep*(1+f.pct/100)));log(`The NEP line for ${l.name} is adjusted by ${f.pct}%.`)}}
 else if(f.t=='dept'){if(f.add&&!S.cabinet.some(c=>c.role.toLowerCase()==f.add.toLowerCase())){S.cabinet.push({role:f.add,...mem(sample(norm(S.parties.map(p=>p.pop))),S.parties,35)});log(`A new executive department is created: ${f.add}.`)}
  if(f.remove){const n=S.cabinet.length;S.cabinet=S.cabinet.filter(c=>c.role.toLowerCase()!=f.remove.toLowerCase());if(S.cabinet.length<n)log(`The Department of ${f.remove} is abolished.`)}}
 else if(f.t=='law'&&LAWS.some(l=>l[0]==f.id))S.laws[f.id]=!!f.on}
function lifecycle(b){if(b.st=='Law'||b.st=='Ratified')return'in_force';if(b.st=='Vetoed')return'vetoed';if(b.st=='Struck down')return'unconstitutional';if(b.st=='Repealed')return'repealed';if(b.st=='Failed')return'expired';if(b.st=='Pres')return'enrolled';if(b.st=='Plebiscite')return'passed_senate';
 const h=b.st[0]=='H';if(b.orig=='H')return h?'introduced':'passed_house';return h?'passed_senate':'introduced'}
function registerLaw(b){const n=S.raNext++;S.enacted.unshift({id:'RA-'+n,type:'Republic Act',number:n,title:b.t,dateEnacted:dstr(),status:'in_force',category:b.tags[0]||'governance',tags:b.tags.slice(),sponsor:b.spn,kind:b.kind=='amend'?'constitutional amendment':'ordinary law',effects:{...b.e},functions:b.arts.flatMap(a=>(a.fn||[]).map(describeFn)),articles:b.arts.map(a=>a.t),bill:b.id});if(S.enacted.length>200)S.enacted.length=200}
function indices(){const s=S.stats,life=62+s.health*.15,hI=(life-20)/65,eI=Math.max(.05,Math.min(1,.1+s.education/100*.85)),gni=3600*(1+(s.growth-5)/15)*(1-(s.poverty-20)/150)*(.8+s.education/250),iI=Math.max(.05,Math.min(1,Math.log(Math.max(120,gni)/100)/Math.log(750)));
 return[['Human Development Index',Math.cbrt(Math.max(.01,hI)*eI*iI).toFixed(3)],['Life expectancy',life.toFixed(1)+' years'],['Literacy rate',Math.min(99.5,75+s.education*.25).toFixed(1)+'%'],['GNI per capita (est.)','USD '+fmt(Math.round(gni))],['Gini coefficient',(.3+.35*s.poverty/100+.1*s.corruption/100).toFixed(2)],['Unemployment (est.)',Math.max(2,12-s.growth*1.2+(s.poverty-20)/10).toFixed(1)+'%'],
 ['Corruption Perceptions Index',(100-s.corruption).toFixed(0)],['Global competitiveness (est.)',Math.max(0,Math.min(100,50+s.growth*2+(50-s.corruption)/2)).toFixed(0)],['Happiness (0 to 10)',Math.max(0,Math.min(10,3+s.approval/25+(100-s.poverty)/50)).toFixed(1)],['Democracy index (0 to 10)',Math.max(0,Math.min(10,5+(100-s.corruption)/40+(s.approval-50)/50)).toFixed(1)],['Environmental performance',s.environment.toFixed(0)],['Public safety',s.order.toFixed(0)]]}
const plebBusy=()=>S.plebs.some(p=>['op','prov','mmerge'].includes(p.kind));
function scheduleOp(op,args,label,ov){if(S.pend)return'Wait until the newly elected officials take office.';if(ov)return OPS[op](args)||'';if(plebBusy())return'Only one structural plebiscite can be pending at a time.';const d=S.dt+60+Math.floor(rnd()*31);S.plebs.push({kind:'op',op,args,label,d});log(`A plebiscite on ${label} is set for ${fday(d)} (Art. X Sec. 10; LGC Sec. 10).`);return''}
const OPS={bgroup:a=>bgGroupToLgu(a.items,a.name,a.city),mdiv:a=>divideMuni(a.id,a.name),mabol:a=>abolishMuni(a.id),mmove:a=>moveMuni(a.id,a.to),pmerge:a=>mergeProvs(a.a,a.b,a.name),pdiv:a=>divideProv(a.id,a.name),pabol:a=>abolishProv(a.id),bcreate:a=>bgCreate(a.mi,a.cell,a.name),bdiv:a=>bgDivide(a.mi,a.bi,a.name),bmerge:a=>bgMerge(a.mi,a.a,a.b,a.name),babol:a=>bgAbolish(a.mi,a.bi)};
function bgCells(m){const M=S.map,out=m.brgy.map(()=>[]);for(let i=0;i<W*H;i++)if(M.mun[i]==m.id){const b=M.bg[i];if(b>=0&&out[b])out[b].push(i)}return out}
function bgFinish(m){m.bn=m.brgy.length;S.ords=S.ords.filter(o=>!(o.lvl=='b'&&o.ref==m.id));reclassOne(m,lguType(m))}
function bgCreate(mi,cell,name){const m=S.munis[mi],M=S.map;if(!m)return'Municipality not found.';const n=m.brgy.length;m.brgy.push(mkBrgy(m,n));if(name)m.brgy[n].name=name;const x0=cell%W,y0=cell/W|0;let c=0;
 for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++){const x=x0+dx,y=y0+dy,j=y*W+x;if(x>=0&&y>=0&&x<W&&y<H&&M.mun[j]==mi&&dx*dx+dy*dy<=5){M.bg[j]=n;c++}}if(!c){m.brgy.pop();return'Click inside the municipality.'}bgFinish(m);log(`Barangay ${m.brgy[n].name} is created in ${m.name}.`);return''}
function bgDivide(mi,bi,name){const m=S.munis[mi],M=S.map,cells=m&&bgCells(m)[bi];if(!cells||cells.length<2)return'The barangay is too small to divide.';const sp=a=>Math.max(...a)-Math.min(...a),ax=sp(cells.map(c=>c%W))>=sp(cells.map(c=>c/W|0))?0:1,o=cells.slice().sort((a,b)=>ax?(a/W|0)-(b/W|0):a%W-b%W),n=m.brgy.length;
 m.brgy.push(mkBrgy(m,n));m.brgy[n].name=name||m.brgy[bi].name+' II';o.slice(Math.floor(o.length/2)).forEach(c=>{M.bg[c]=n});bgFinish(m);log(`Barangay ${m.brgy[bi].name} in ${m.name} is divided; ${m.brgy[n].name} is created.`);return''}
function bgMerge(mi,a,b,name){const m=S.munis[mi],M=S.map;if(!m||a==b||!m.brgy[a]||!m.brgy[b])return'Pick two different barangays.';for(let i=0;i<W*H;i++)if(M.mun[i]==mi){if(M.bg[i]==b)M.bg[i]=a;else if(M.bg[i]>b)M.bg[i]--}
 if(name)m.brgy[a].name=name;const keep=m.brgy[a];m.brgy.splice(b,1);bgFinish(m);log(`Two barangays in ${m.name} are merged into ${keep.name}.`);return''}
function bgAbolish(mi,bi){const m=S.munis[mi],cells=bgCells(m);if(m.brgy.length<2)return'A municipality needs at least one barangay.';const cc=c=>{const p=cells[c].map(i=>[i%W,i/W|0]);return p.length?[p.reduce((a,q)=>a+q[0],0)/p.length,p.reduce((a,q)=>a+q[1],0)/p.length]:[0,0]},me=cc(bi);let best=-1,bd=1e9;cells.forEach((_,j)=>{if(j!=bi&&cells[j].length){const q=cc(j),d=(q[0]-me[0])**2+(q[1]-me[1])**2;if(d<bd){bd=d;best=j}}});if(best<0)best=bi==0?1:0;const n0=m.brgy[bi].name;bgMerge(mi,best,bi);log(`Barangay ${n0} in ${m.name} is abolished.`);return''}
function bgGroupToLgu(items,name,city){if(S.pend)return'Wait until the newly elected officials take office.';if(!items.length)return'Select barangays first.';const srcIds=[...new Set(items.map(x=>x[0]))],prov=S.munis[srcIds[0]].prov;if(srcIds.some(i=>S.munis[i].prov!=prov))return'The barangays must be in the same province.';
 for(const mi of srcIds){if(S.munis[mi].brgy.length<=items.filter(x=>x[0]==mi).length)return`${S.munis[mi].name} would be left without barangays.`}
 const M=S.map,id=S.munis.length,p=S.provs[prov],cellsBy={};srcIds.forEach(mi=>cellsBy[mi]=bgCells(S.munis[mi]));let pop=0;const mv={};
 srcIds.forEach(mi=>{const m=S.munis[mi],tot=cellsBy[mi].reduce((a,c)=>a+c.length,0)||1;items.filter(x=>x[0]==mi).forEach(([_,bi])=>{pop+=Math.round(m.pop*cellsBy[mi][bi].length/tot);(mv[mi]=mv[mi]||[]).push(bi)})});
 const n0={id,prov,name,pop:Math.max(5000,pop),city:!!city,huc:false,icc:false,lean:p.lean.slice(),hist:[],bn:0,dev:50,ie:+(.6+rnd()*.9).toFixed(2),brgy:[]};n0.mayor=person(n0.lean,city?23:21);n0.vm=person(n0.lean,city?23:21);n0.sb=Array.from({length:city?10:8},()=>person(n0.lean,18));n0.exo=exo();
 srcIds.forEach(mi=>{const m=S.munis[mi],list=mv[mi].slice().sort((a,b)=>a-b);list.forEach(bi=>{const ni=n0.brgy.length;n0.brgy.push(m.brgy[bi]);for(const c of cellsBy[mi][bi]){M.mun[c]=id;M.bg[c]=ni}});
  const keepMap={};let k=0;m.brgy.forEach((b,bi)=>{if(!list.includes(bi))keepMap[bi]=k++});for(let i=0;i<W*H;i++)if(M.mun[i]==mi&&M.bg[i]>=0)M.bg[i]=keepMap[M.bg[i]]!=null?keepMap[M.bg[i]]:-1;
  m.pop=Math.max(5000,m.pop-Math.round(m.pop*list.length/Math.max(1,m.bn)));m.brgy=m.brgy.filter((b,bi)=>!list.includes(bi));m.bn=m.brgy.length;S.ords=S.ords.filter(o=>!(o.lvl=='b'&&o.ref==mi))});
 n0.bn=n0.brgy.length;S.munis.push(n0);n0.huc=n0.city&&n0.pop>=200000;reclassOne(n0,lguType(n0));srcIds.forEach(mi=>reclassOne(S.munis[mi],lguType(S.munis[mi])));syncGeo();
 if(typeof sel!='undefined')sel={r:p.reg,p:prov,m:id,b:-1};log(`${name} is created as a ${city?'city':'municipality'} from ${n0.bn} barangays.`);return''}
function lguCheck(items,city){const srcIds=[...new Set(items.map(x=>x[0]))];let pop=0,cells=0;srcIds.forEach(mi=>{const m=S.munis[mi],cb=bgCells(m),tot=cb.reduce((a,c)=>a+c.length,0)||1;items.filter(x=>x[0]==mi).forEach(([_,bi])=>{pop+=Math.round(m.pop*cb[bi].length/tot);cells+=cb[bi].length})});
 const area=cells*10,inc=pop/1000*(city?2.4:1.4)*.7,notes=[];if(city){if(!(pop>=250000||area>=100))notes.push(`A city needs 250,000 residents or 100 sq km (this has ${fmt(pop)} and ${fmt(area)}). LGC Sec. 450.`);if(inc<100)notes.push(`A city needs PHP 100 million in income (estimated ${Math.round(inc)} million). RA 9009.`)}else{if(!(pop>=25000||area>=50))notes.push(`A municipality needs 25,000 residents or 50 sq km (this has ${fmt(pop)} and ${fmt(area)}). LGC Sec. 442.`);if(inc<2.5)notes.push(`A municipality needs PHP 2.5 million in income (estimated ${inc.toFixed(1)} million).`)}return{pop,area,notes,ok:!notes.length}}
function divideMuni(id,name){const m=S.munis[id],M=S.map;if(!m||m.brgy.length<2)return'A municipality needs at least two barangays to divide.';const cb=bgCells(m),cen=cb.map(c=>c.length?[c.reduce((a,i)=>a+i%W,0)/c.length,c.reduce((a,i)=>a+(i/W|0),0)/c.length]:[0,0]),sp=a=>Math.max(...a)-Math.min(...a),ax=sp(cen.map(c=>c[0]))>=sp(cen.map(c=>c[1]))?0:1,order=cen.map((_,i)=>i).sort((a,b)=>cen[a][ax]-cen[b][ax]),half=order.slice(Math.ceil(order.length/2));
 const nid=S.munis.length,tot=cb.reduce((a,c)=>a+c.length,0)||1,share=half.reduce((a,j)=>a+cb[j].length,0)/tot,n={id:nid,prov:m.prov,name,pop:Math.max(5000,Math.round(m.pop*share)),city:false,huc:false,icc:false,lean:m.lean.slice(),hist:[],dev:m.dev,ie:m.ie,brgy:[]};
 n.mayor=person(n.lean,21);n.vm=person(n.lean,21);n.sb=Array.from({length:8},()=>person(n.lean,18));n.exo=exo();half.sort((a,b)=>a-b).forEach(j=>{const ni=n.brgy.length;n.brgy.push(m.brgy[j]);cb[j].forEach(c=>{M.mun[c]=nid;M.bg[c]=ni})});
 const keep={};let k=0;m.brgy.forEach((b,j)=>{if(!half.includes(j))keep[j]=k++});for(let i=0;i<W*H;i++)if(M.mun[i]==id&&M.bg[i]>=0)M.bg[i]=keep[M.bg[i]]!=null?keep[M.bg[i]]:-1;m.brgy=m.brgy.filter((b,j)=>!half.includes(j));m.pop=Math.max(5000,m.pop-n.pop);m.bn=m.brgy.length;n.bn=n.brgy.length;
 S.ords=S.ords.filter(o=>!(o.lvl=='b'&&o.ref==id));S.munis.push(n);reclassOne(m,lguType(m));reclassOne(n,'municipality');syncGeo();log(`${m.name} is divided; ${name} is created with ${n.bn} barangays.`);return''}
function abolishMuni(id){const m=S.munis[id],p=S.provs[m.prov];if(p.mun.length<2)return'A province needs at least one city or municipality.';const C=centroids(S);let best=-1,bd=1e9;p.mun.forEach(j=>{if(j!=id){const d=(C[j][0]-C[id][0])**2+(C[j][1]-C[id][1])**2;if(d<bd){bd=d;best=j}}});const t=S.munis[best],M=S.map,off=t.brgy.length;
 for(let i=0;i<W*H;i++)if(M.mun[i]==id){M.mun[i]=best;M.bg[i]=M.bg[i]>=0?M.bg[i]+off:-1}t.brgy=t.brgy.concat(m.brgy);t.bn=t.brgy.length;t.pop+=m.pop;S.ords=S.ords.filter(o=>!(o.lvl!='p'&&(o.ref==id||o.ref==best)));const n0=m.name,tn=t.name;dropMuni(id,S.munis.indexOf(t));reclassOne(t,lguType(t));syncGeo();if(typeof sel!='undefined')sel={r:p.reg,p:p.id,m:-1,b:-1};log(`${n0} is abolished and merged into ${tn}.`);return''}
function moveMuni(id,to){const m=S.munis[id],p=S.provs[to];if(!m||!p||m.prov==to)return'Choose another province.';const old=S.provs[m.prov];if(old.mun.length<2)return'A province needs at least one city or municipality.';old.pop=Math.max(20000,old.pop-m.pop);p.pop+=m.pop;m.prov=to;syncGeo();log(`${m.name} moves from ${old.name} to ${p.name}.`);return''}
function mergeProvs(a,b,name){if(a==b||!S.provs[a]||!S.provs[b])return'Pick two different provinces.';const pa=S.provs[a],pb=S.provs[b],L=(pa.districts||[]).concat((pb.districts||[]).map(d=>({n:0,munis:d.munis.slice()})));L.forEach((d,i)=>d.n=i+1);pb.mun.forEach(id=>{S.munis[id].prov=a});pa.pop+=pb.pop;pa.districts=L;pa.dist=L.length;pa.distStatus='scenario';if(name)pa.name=name;pa.mun=pa.mun.concat(pb.mun);pb.mun=[];reclassOne(pa,'province');pa.pdAuto=true;const nb=pb.name;dropProv(b);syncGeo();pruneRegions();fixCaps();if(typeof sel!='undefined')sel={r:-1,p:-1,m:-1,b:-1};log(`${nb} Province is merged into ${pa.name}.`);return''}
function divideProv(id,name){const p=S.provs[id];if(!p||p.mun.length<2)return'A province needs at least two cities or municipalities to divide.';const g=splitK(p.mun.slice(),2,centroids(S),S);if(g.length<2)return'The province cannot be divided.';createProvince(g[1],name);return''}
function abolishProv(id){if(S.provs.length<2)return'The country needs at least one province.';const p=S.provs[id],C=centroids(S),n0=p.name;p.mun.slice().forEach(mid=>{let best=-1,bd=1e9;S.provs.forEach(q=>{if(q.id!=id&&q.mun.length){const d=(q.cx-C[mid][0])**2+(q.cy-C[mid][1])**2;if(d<bd){bd=d;best=q.id}}});S.munis[mid].prov=best;S.provs[best].pop+=S.munis[mid].pop});p.pop=0;syncGeo();if(!S.provs[id].mun.length)dropProv(id);syncGeo();pruneRegions();fixCaps();if(typeof sel!='undefined')sel={r:-1,p:-1,m:-1,b:-1};log(`${n0} Province is abolished and its cities and municipalities join neighboring provinces.`);return''}
function recall(kind,id){const e=kind=='p'?S.provs[id]:S.munis[id],off=kind=='p'?e.gov:e.mayor;if(S.dt-(S.lastLocal||0)<365)return'A recall cannot be held within one year after the official took office (LGC Sec. 74).';if(S.next-S.dt<365)return'A recall cannot be held within one year before a regular election (LGC Sec. 74).';
 const p=cl(.25+(60-(e.dev||50))/100+(55-S.stats.approval)/200,.05,.9),yes=rnd()<p;log(`A recall election is held against ${off.name}: ${yes?'the official is recalled':'the official survives'} (LGC Secs. 69 to 75).`);if(yes){const n=person(e.lean,23);if(kind=='p')e.gov=n;else e.mayor=n;log(`${n.name} wins the recall election and takes over.`)}return''}
